import java.util.Set;

/*
--- Day 1: Trebuchet?! ---

Something is wrong with global snow production, and you've been selected to take a look. The Elves have even given you a map; on it, they've used stars to mark the top fifty locations that are likely to be having problems.

You've been doing this long enough to know that to restore snow operations, you need to check all fifty stars by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

You try to ask why they can't just use a weather machine ("not powerful enough") and where they're even sending you ("the sky") and why your map looks mostly blank ("you sure ask a lot of questions") and hang on did you just say the sky ("of course, where do you think snow comes from") when you realize that the Elves are already loading you into a trebuchet ("please hold still, we need to strap you in").

As they're making the final adjustments, they discover that their calibration document (your puzzle input) has been amended by a very young Elf who was apparently just excited to show off her art skills. Consequently, the Elves are having trouble reading the values on the document.

The newly-improved calibration document consists of lines of text; each line originally contained a specific calibration value that the Elves now need to recover. On each line, the calibration value can be found by combining the first digit and the last digit (in that order) to form a single two-digit number.

For example:

1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet
In this example, the calibration values of these four lines are 12, 38, 15, and 77. Adding these together produces 142.

Consider your entire calibration document. What is the sum of all of the calibration values?

Your puzzle answer was 54708.

--- Part Two ---

Your calculation isn't quite right. It looks like some of the digits are actually spelled out with letters: one, two, three, four, five, six, seven, eight, and nine also count as valid "digits".

Equipped with this new information, you now need to find the real first and last digit on each line. For example:

two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen
In this example, the calibration values are 29, 83, 13, 24, 42, 14, and 76. Adding these together produces 281.

What is the sum of all of the calibration values?

Your puzzle answer was 54087.

Both parts of this puzzle are complete! They provide two gold stars: **
*/

// pair programming with a non-programmer, took me ~2.5 hrs
public class Advent1
{

	public static void main(String[] args)
	{
		int total = 0;

		var lines = input.split("\n");
		for (String origLine : lines)
		{
			// Part 2!
			var firstLine = processedLine(origLine, true);
			var secondLine = processedLine(origLine, false);

			// part 1:
			String first = firstDigit(firstLine);
			String last = lastDigit(secondLine);

			String val = first + last;      // "3" + "4" == "34"  !(3 + 4 == 7)
			int lineValue = 0;
			if (!val.isEmpty())
				lineValue = Integer.parseInt(val);

			total = total + lineValue;

			var str = "current total: " + total + " (line value is " + val + ")   for line: " + origLine;
			System.out.println(str);
		}

		System.out.println("total is: " + total);
	}

	public static String valueToReplace(String line, Set<String> valuesToReplace, boolean fromStart)
	{
		var actualLine = line;
		if (!fromStart)
			actualLine = new StringBuilder(line).reverse().toString();
		for (var value : valuesToReplace)
		{
			var actualValue = value;
			if (!fromStart)
				actualValue = new StringBuilder(value).reverse().toString();

			if (actualLine.startsWith(actualValue))
				return value;
		}

		return "";
	}

	private static String processedLine(String line, boolean fromStart)
	{
		var set = Set.of("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "zero");

		var str = line;  // "dttwonezbgmcseven5seven";
		do
		{
			String toReplace;
			toReplace = valueToReplace(str, set, fromStart);

			if (!toReplace.isEmpty())
				return line.replace(toReplace, convertedNumber(toReplace));

			str = (fromStart) ? str.substring(1) : str.substring(0, str.length() - 1);

		} while (str.length() >= 3);

		return line;
	}

	private static String convertedNumber(String input)
	{
		return switch (input) {
			case "one" -> "1";
			case "two" -> "2";
			case "three" -> "3";
			case "four" -> "4";
			case "five" -> "5";
			case "six" -> "6";
			case "seven" -> "7";
			case "eight" -> "8";
			case "nine" -> "9";
			case "zero" -> "0";
			default -> "";
		};
	}

	public static String firstDigit(String line)
	{
		for (int x = 0; x < line.length(); x++)
		{
			String val = "" + line.charAt(x);
			if ("1234567890".contains(val))
				return val;
		}

		return "";
	}

	public static String lastDigit(String line)
	{
		for (int x = line.length()-1; x >= 0; x--)
		{
			String val = "" + line.charAt(x);
			if ("1234567890".contains(val))
				return val;
		}

		return "";
	}

	private static final String input =
		"""
dqfournine5four2jmlqcgv
7ggzdnjxndfive
twofive4threenine
dttwonezbgmcseven5seven
5vsrcnine
95zzbjck
gkoneight4fivekvktltnine
fiverckdmgbfthjdqpmpgdkmcklqtqc365mqtwo
44sevenhvstcbgkhm5foureight11
dprrtrngrfccz4eight4two8sthmfive
6twofive4seven7nine
four1sevenbfbnqvkbfoursix7
12xpdghpeightqvztrsslgsix5smlgfjhcpst
8dhzdtbeightfour3
pttdtmhg4
6eightsevendbtbxnqzxds6
twothree5nxglqlc9
nine6lqhnvbpxoneseveneightsxjfkz4vr
three28jxdmlqfmc619eightwol
26jtdpgqjzshncxvlljfour
qxvpsctgx1
28286qdjjlgtdtnsm3hk
9hcj6nine
nineseven9sqtrpfour
one1eight4sixzltzrkthree
threevlgfxhnf6seven6nine68
sixonesxxbxvfnkt8
8fivefivefour7sxsrvdrz
oneone7
ndtkjbsix6three9gdsjlljtj6six
cfmrfgjqgrzcmsix5
3threefour62three3vrmnmgx
kckdghseventwo1758
mdbqqjmpvonetwo1six31fourntbfb
lkjhjdthree3
qthseven61mpfnnhm6fivecnhz2
twojrfgzjstjvlngnpqcj8grtnvxmzbxkfrvqmvnmvmbdr
sloneightkqbgcpnv8kqcmzfouronesevenmrfjeight
xdxdxg9seventwo8xcq1
dpdgxzk7
18six3twoone
1twoseven3five
46tkbclbkleight64
tjprpjbshr2seven1pgfqmbmjlvsv
3mbjccssjgtdttvbdhdfxvldpmhcpc
lgfrkpsfvz5ppgqphtwoznjtgxdjpm3
mjmlsevenggsbjbtsix9nineone
jqfqjqhthreenine7eightklkttdkbtmpp1
trptrkbone52eight6
onetmvsrjlbqlninesix8
rone9ktvdqkdgl1
twosix5sixgrfdft54klf4
thrmone3eightsixfive
three4one
ppthg2three1one
7vt426
22foureight6
fourxbhmone56seven8eightnine
vhmsd171rgkhpgfhffnhkvt
xgbzxszsgtthree4
rclzfsn5twoeight
989nine2seven
eighteight5fivensix8
dfxzz5qcqzsjsg
d3eight54
5knflhntzthreeseventwo
threeonefour9oneninebsfpq
hjhgtjgtwotrsffive8hfntm
sixpmhzqrlkrthreefour1pcgvz96
5three31xqcsshkkqtfblffcmcntfour
zghcfvjsfz29nine
3vvvrlrjdztlhqqm88
39nine3seven93
1fqsgnjzrl6lrzsczc
threepldztlnvnzdntqllpr19
ninekgqqrgttfntrhjzlvninelr3
94eighteighteight
two13txmtlqxskhltkrvbjrzm97five
dbmjvszjtb17
twogpfttmhp8two13
four4bqzqscdbctssgxfzjjntwonfcktjrtnxskjpkhvlfjt
ctxxvdsvsvjzchmxvxceightthreembnlg5ninevmcbgsvbh
fpbrpfourqmrfcnpvxg8onehkbbgbsnnt
4zrrgsevenfour
6eight9foureightxlgdn
693rzcnvlfrv
bcftntcfl4jxbccpcmjeightcrxsjscmxdeightmhqbnpdvcfour
six83
xl4
njslckcbdfvkmkdk9eight
ninenineeight4nine
jkzvq3fourzzvdzdft
bfqpb9
eight6nlzdskjfourbmdvcrcgrshbjcxfour2
7zhlxtqtbjxqbszdtwonineeightjcl9
fvcjzxd5sevenfivefqnvkjthreeseven
3cxmpzkng3
8x2
nineeightsevenfourpfzzflnp97
2lkjpfhnpn7gbtztgxtnmclzdtdh33eightstbfrvxqz
nv8
3one7eight
ninetwortwoeightfive8ls
shncxrjqnjttvvzvnl6
ninethree963
mjcfrzjhr33csjxrtmm
five17
84bdfnptmffourfbqslsqeight
onegrzpdj8three2one6fsk
eight33gxpcqvpmeightk
6fbsfclhninetqj5twobxcz
119sixnjmxmvv
825bhceightone4jjdbvrzt2
xjchvkxxhg3sevensixseven3kmgqfmbgmbjnrq
l2
36hcmfnbmsevenfivetxhhgjdlq1khkk
eightj47five4sqtwo
6nineeight9
g2drvxqvpnbjfqxhl
vglkfour9rlmhsnine
onefivezr6rrtddnrg
3threellcbhjhjzqfive5
ggbmhzkcone2
23nclcqvjdzqcrpvsmnpzsfg3five
two5eightddxqgpm8twoseven
nrvtvlhrlr3tvpck1ghbvzxhjkneightgzxgtcddk
7lsxfjhqz
28four
mninetwo3
1fourfxqjpggbpb9threelj
seven3pzkfbqdstdgkrskqrlbg7fzfour4n
btctmct9three6threegkqqkcskfs8chvmcl
threefourskdp6twob
7three6five6eight3
5spkb6
34msnt
5bkqbzpgmjzeight
7g2onefour29fourfour
9fgsixzkbscvbxdsfive6spjfhzxbzvgbvrthreeoneightn
rpbd255fournine
277five
eightseven7sevenllninefive
rpjcmzkthbvdflbhxxkpv3oneplglgmv
xqktwone5jkpxvnptjeight
67one
cgxfhzsnrsjp3kjgzrlbhzh
fiveqqjljzfcmbfqvkscpzscpseven4nine1xvjlgk
tflkxnml5vptclnhkgdg11c2seven
sixeighttdbczshg82threepmjnxrvcnine6
nineone81mkltdkfgxtsevenfive
8zgx
cvb4kv22gp
61bjllhkblllqx8bmr5threesix
9cjfgb1bxncrgfhtmg973
eightninefour5twosixbsvnsndhtghtmfive
seven1bbfrvdcsthree2
cfzd8hvqscjxqf9
sixvfkcgmvqn9vmbzccdmqqgxmfxmnqc95
qqrqnd8twofive7czxtjnmxx
threebdmrlnxnlmdbzbv4
nm91vblgfourtsjp6
six96
sevenrjvbxptl9onecrlz
dvdbrmchgpninenine4onedjcfoneninetwo
hcrrgnlxftwo6four
threehcrfknsnqmg49
2tqbrkxgtdztjkdcnsix6three
mktnzjn58qspzpqdr7
dphvck5fourbmfnskkh72five78
one7seven7
bmpnljsxhfmtwozrhvdv8sjsrmnzlcjvjqcfgffhkjcbx
7one6874
three9tfx4
eight9pqhseightndgbv6
39jgmbzrzkctsix
1676
8xtpdhzfd8three44four8two
sixkvlppxqktkdqjsgjgz5
twoonehbgsdhpxkdvnpr3ncrgbqzfvsbcdsix4
39kpdxsp368seven2
xfljqfbz5tzpldspxvgc
fourqb6twocfljflzqqd
5889cxvxkstlld75rnlgzpgmhcmnx
84zxqsqvb
fiveksvtbqz9934
onefour96four78fourkbkhdhg
h61three2v
nine9jlbrfmgjv2kkfive
bjhktrjmfninexxnjhrvq7
fbcxlvgkkjcmpdcz7
mnleight3oneqqttlp
eighttwolffour1
onetqfghfourbmf5
four1qfive4
9fvp
cxxn5qzcm
one7hzjpnvhtdq
pxmht4fprcftwofive7gsixcqbmrd
three9fivesixrdqrhcqrqbl
6fggvr
ninesixmxvdcqgxcmskl115lskkp
sevenqkmqxltfive191lfbtfvzsixseven
ninemjnjgrlmnlseven5eight9
fhjjtxzksseven7fourthree
rfjksvfour26vqbdrbxc
6zgkfive8mhgxbsm
1njpjv696
4lrthsevendnsmseven
l4hxvjvlfpjmdbvdjzrhkhpmklnine7fourfour
2qtkhnineeightone
fivexhrxrzxht1foursix
sixlzcgllrqlhghzn1hdhgltcntfivefourfive1
dpkzdbzsgq9threecst7znsjgdmmhx1
three497lp388
llnklrkfr3
ltkkv481pzhqzkmhskxlznineninekcbrphlp
fivetwoseven71nineljsbc49
bvqsxnkpmzsevenhdpvfvlb2eight2bdxp3
onefour64
8xfdtfnqvhzkhvszeight5
threethree4two
z5two2fp
fourvjmcghrcfoureight3
lhztwo9dzhpdgn675
jnine4two49sixskv
9phbnnsoneqtpvvzbx5xzc
mtjfxzzhzdjvfmrc1
4ccszl3fiveseven55lfmktz
five27three9mgrnjcsbpd
6eight115five4c
two63fjlkgninepthmone
22ddxpbbpdseven
zg7
five3gvbthree6hjseven
x6six58nine
seveneighteight75three9two9
onevlpdgsnl3
sevenmbvqmjhfnzmgsqp8qnskjzptpppbcfhck2
7bpldrqr6fourpsntqbcqhfive
twothvddvmlbqknrj9pgpsjndbrmrgkgf
sixthree38onefoureightmvdtnn
vkqcnfkkc6
sixeight9
65fouronemklfgqbpgnvlvcvhjcdkq
three5five
981gxpsgqxjktwogninezgnf
cfnnzfnlmfqtwofour8fourxg5
45mpgbgzctwoqlsxmgs8
5nhzlcb6four6pzjjlr4ninej
gnkoneightprhlrseven7
1rzsq1seven3eight
sixnine9eight8eight
lcszz858
pdgbgjxthreethree3threeonengk
8zpzpttrqtwoninek895
634jgvbvr
nine8mvr
5seven2psmtnmzdfivesix
56ninerqrlzqvszrght6zkgtvrphpnvthree
5fiveone
43three
9mdtghvfjdqqbrmeightfour92tlstxvrhthree
b8
ninehpnmdhjqjl5ppptrd
41fournineeightvxxjdthreeeight
ntwonefnsdpnine8sevenbjzxpfive
6oneclxflmxvtwo1
9jbpfnvfsjblmxrprml5
68five7sfgxjqxrcjmninerzgxnhjpzkdhxzbg
1vztdlnone2lhrhx
6lrmdrxqlsttwovsr9eightpbmqcxn
2zjchhdbzhc
tsgntwomdtsjtdrthree9
7threethreedprbrvngxpfour
fivestvv3six
6one9sjlzjtxxnkbckdmc
zxqzmcz3eight
lndh86xphvbnine
fivesix3sixf93hbbptwo
3cxpbl
gsnqeight8kthxzrdkskjkmcmsknine5
67twoxdqninefour
fivefivehtczfmrhvlsevensevennbjkvhz84
cmbgm3eightpbmgjhsp2
fivepdhtcpvg3ninenlhpgdlnnine6fblsmlz
kcnsfsfhjbcffctznvp1
qzrkvhcds4gklftv
xslgkktct7snbxnplbk3five
zspb1sevennine76one
twonxtngxlrftltqggpftj3eight1gsrkbbclll
474jxtncx
bxsqsb8
svsvvtzddklkrxmpd2
xbvjfmcnine2znbqn5eight2smvkgpclvs6
tnlpfivem7
7seveneight2dfiveonesix6
fspcrlcthreej1seven4
7nineeight3hzfour
9fivethree
four5ggbseven
5hsv
1ppkkkhfzn
pkfzkpv9mtktjvrssdftslonebpmhf
8fhfqmzseven
six89htmnpmqsixzvxl
9mbkcbnmptpkhqvvzxftss7
48five
eight8118four7qsjb
cpghtgncpkkxtrvrsgl81eightcfzsjfq6
ninecsthl8onefgpmc
3threehnrone5dzcfdtpf2hdlnrxnmnhjqqqn
5ninesix54
lnzhtwo9446onefivefour
8two427bvcdkckdgz8
6six35seven
six2fcpzhbn6fivekm34
httmgldjfqnnhktmnhj4dsmffzknbq674
9nxrtsmqbcrgghqtx6kdnrfjq
thhmbpjldslpthkfxcfive1zrjqtpvjs8
cjtbcn7five9nlpgsoneone8
seven6eightx176ffrvml8
eight9jntmr4sevenmzjb
mxk51gt
three21foursevendbvm
zqtdz1ninemmhkjfiveeight
98xlpkzb
34two5four2cvtcjfdh
jvndgrtjonethree6
ninefivefive1lfqjqmptxvthree
kkxfqqkf49
3sixseven3dzpvnvt51rnzljdprb
hpzpdrnkthreekct1mqdvljhrls3
six6sjsljgvgzhrzqpsznh3fivejpxsvqccrc
cpvlr7
tdgthree8twofivexxrvct
62sixmt9ninefour
ninesevenfourzfzl43qssqrkktpnzjv
8mfztzthreeldnjgsfseven
356
6vrlthreer9sone6
sixs8six5sevenvnkgbmxj2two
8eightpglsknpxmsixjgqcftmvprjlcdsfks
3dlkbc1
five5eight1
7seven49
ggoneeightgcfnfkgbmlfourdls23
seven6jdpxxkfone
lfive715
2ninefivej2sixeight
ttwonethreethreesixzbqz7
zmbqqcd8ztp46567
nineeight11
zhgsixthreejffqhzdfvfxjpfmjqqkm36one
5vgftjvqkxj6pnctdcrktwoneq
9ptmkf8six
lbjxvnfiverjppbtrhf6xbdnsltlnrqsgmx8q
365pxj63gshpg
vlq5zhgj4
98hc13nnrzfzschg64
2twopq76kpmjdjflkqzxlvjhr
rnvmblqhq1
8j273qfpfkz
dsevenvvdmxhhcd1dkz
lkqhrxkmp96fppvsdtwombkfour
3one7dzpbhsrdf5
159ckggpfzlgntfrddvfiveeightthree9eightwodnp
eightseventhreeseven1
mrzpk8
fmvxth2eight8hjmfkdxjh
3threeone
nine5sixsixnzlqhsc
xtxbgtntwosixfour85
3eighthz4twoqmlhrzsevenkcqhgrghrd
12ldchpqzm
zcfjz5sixmqqmfsv9six6
sixlzcdtd3qlcjqzrtthnine
1one6nine
11xqblttcrdvgb7mdqkphrbdx
xbcc4mtgf5
sevenfourmthree1hgpnmvcvgshzvcsjdbqqgmt
v5xmghdgbkvnine
29mkpfz7
jptwo4lqlrh2onefive7jhcngr
four6twosixsthjqpgh2
pctrvkmc82four2958
12eight3
7jbqeightlbbnpsvvdfrqccb
peightwo6sevenfoursixdmchsd1
53dhphzvhnknt65ninefive
86fivegpnhl
tpcspvvncglcsqjzlqrfivejgfl8zspdltrd7
mhpskcvhn3bkjlmqd
onetwo4lxmsnddzfbxcdcscjxxrzsvvzg3nvtrpncvpmc
fprqq1bpqxvjmblc17
four7ninenineksjcktcbtzsmrfr
3nineccrnhtgg2knczqnnineoneqsgm
4xnkljmg7lmfvrhxm96
five458eighteightxcgrnine
klrzfbrpkmtptdscktmcsqg5xonesix
vtmh1glhzlkmrlgfourpsbhtbrvdz57one
9eight53threethreepgnc
fourseven3fivefq57
5sixsixthreegdsrhkhdlk3six
v9xqhpzkfivebnjslbzh548
jssdslcxxv3sdhbqnine5sixeight2
vr1
eightsoneqrrqfoursixzngsths9three
ltwoltrplmlkzz5sssjmzgcjsixfivejhms
49one
2sevenfivethlgxmxssnvlsfst4
8slfnfsfk
fourszbtpvvlvppsqbsprthreexgrlp3zt4
seveneight8rhonectrmxrjvnnthreetxmfbvxtlt9
twofive6eight9
zqxpxlzjm3hmzjzgoneeight1seventwo
9xbmqqtkstflg6onem2tdfsfjnxdmmzlrcnpm
pgcxbqvvj6
xfsix893
7four1
63five
tr9chvmlhhv6
jxc2six452
11zvz
oneqkhstmkhb11fourninezs37
3mxf3slhhs
sixgdnljsfkfnffp67789nvgc
sxptjdmqfv1eightsevenfpxpdnrtnqkdxhnzdm
grdgt9ninedxnqhrts
8sevenxcsl1
fiveeighttwo5
bgroneight2pgzdpnzgchkq1
5twozc62foursixeight
six61
cbxzoneeight1
hntwonebmslklfkfgpngvffour5
1262ninemdjsrdk
roneightqnjseven2
rmnpjzflcmqdrdseven3
ltwollzgvr1fiveeightjvv7
kkc5fourfive89
cqnnhjxp4dtt
jeightwo1fgtlfpsixtwo9pptcpmjjsixone
832
9eightkhlprvq7seven
ninegeightbfvnvvnpslspcmscvqcqb6
jgksh2lkss6onexznvfhq
flqhlpkzjvq3qvvgvjscr6v9eight
hrgeightwo8
3fvpkbrhqchlbsxhlqfone3eightmhtxbrninerbkrsnxbjg
871eightnineq5f2
6jnonergcjfvkhfive
one47fxgvgmoneoneoneg
5xktmbkqftrlvztctxnqprpnine
eight4tfvsbtmhtwol
rbjdrmbcrs9chvcj7s
eight12bdzqtvnqeight27rpt
fq713oneone6rgrnd
cdt96
dbfrd4rczmbgnmfrltdlpbseven7lqhfive
fourdxxkqjfpjxbcthzhbl67eightzks19
2four5ntghsdcsdrjpbrtrt3bzgbtfnknine
tvmnjgcsixnine8zrc39five
5kcbfkj61three9tsqpvzdd
qsmseventhreeone4twosix
twosix2
jzsmxs9plpsixpqxffive
sixthreeseven4flbct
mpplmsrjvz9
8ttgt9ninesevensevengnprjnvxpjz
8gmpgvbfjcdsnkcth9bbnqsqhqqzeight42
nk5b
four98six83five
415rqgdfsix
mqrkmbvtm668
6453twoone
9fiveeightseven4gsshznxbkb5
seven3ninedgthree
jckgvtvrs3six3trrzfrxfnm8
98fivexxdqpmv74fbthtqqfourvttxnck
fivenineonefour46tccfkrsrpqnxhtm
twobdsqhnscrkbzt19
llmccgn8
6eightoneonen57
meightwo1cjqsm3sixlrr
98842
twofnsvbsxkxrzghhrz29
tzfjthreebkkljhninetwoone6zgpgsgxq
fournkcgf85seventwo
642
four1oneninejbstfcdgjkjtppskglj1
4four9eight2tnphxvfour
sixjhcnxkksxthreeseven1four1
rb34pqtnnfive2sevenone
33sevennlnhrkkbshonefnrqq72
3sevenfourlmqzfdjrq
tmttpfb4mghtcpnine
nhlqlcxff8
fiveone5gxg
fivecrjmsgljxb1mqmffour8mgtdxsjsix
1jdkvzfmbq
ndzqgk6
threeg7twofour2twossldnmthree
5rsltvdtworrglclfpctml3
nine6fourmcqbhbvlmzgnfqtbcs
5eight92
ninefivefour3kbnmrdmxjg2
73vprclhthzz8
ninettjnnkrsix9kvxjknzkmsxtvdn
bgzfv59fhsvcjvlgmhhzph58
threeonefivecgjstcmp57
9onefoursix
sjqjvd4three91
9ccdjqfivefourfive6mrnkjqf
7lzdrzjheightthree6
43
nineb8sixqqsxrpn
fgkj15eight6gggndbjxvthree
one3sevenlfjqmbmssgbzs8pzjptxgvq
77fiveqpjpfdqteighttpfh
2333twonezrr
8p4cxnjvbjlh9ninesix6
ninefour95
67twosevencktwopjcmcxr
9four1threejbrdmtkzn
ninenjhstmmmj3four
4lnqjqtwo3zxfznvp
sixfivesrxnttwochrkdrr7
4three1
tfeightwo9two69five
oneseven3sixfournnpkhhx9
mdl8kfpvthree
fxcxgmq5three3ninehdc8
one9eightfiveonernhbcxjninethree
9three3fcpgxksix
nine346946one
hzkpbmdzdmsfkrbxvs6pnmqsevenlnr
kzsgmsix5
kdjdvvdl2
8lcpfkhdltwo
xjzfbgrmvxprqpflpbk9cnpxdkgmvvjz8vbrjhxvthfsjkk
onefive7
tjqmxncdbmsjznine1zlr
648bhzlqnlvrshdgzonefive
eight2sixtdzznchf1seventwo4
sevenzcmpbfbzdvjlztpx62
5961
97192fivethree
seven1mcxnqqzvpp5
8qn1eightseven
hcrrthreesevenlkvhfbj96twonine9
two8four
hpkttfdpgb16
19oneseven2onerl
347seventwo
eight4threempfbxbssrrkscnc4eight
555qrppcplpgtworxgbgdjdhltwothree
v9627
twoninenine72tkcbk
one5jhczrlqmhr
qnhr4xlckprn9x3bzrdbfrdql9
lgtdv99kmgjjkzfive
lrclbljqqpninerrjptvpfour2
fiveltkcgdvgkeight7seven
twongdsevenfivefive3foureightwonn
8svdmkflj
rlbf4sevennc4jxsskjgktwodsxgtlkthree
seven4nine4fivezjfsjghbcninefk
drghcjthreevstpdfth6sgqtx
zkfthreefptvnvb9five
gjcqspnkztlqdnzl6
6nineqzgvhcnhjxbmtkcfm8one5five5
threesevenseventwoqrcvpvvrdljfone3
v44nlcdx8eight
eightseven3bmfzeightzccxqk6ftlsmfp
seventhreeseven3
7eightgvxcdxzplrthreelqgbhvpqffivefour5
8coneckchx5pfive
xhbbmsvjnonethree4
lnktfknbqfive4seven
8prvncdq97hjjltzreight
2dfktgjgdrvfour
9onesixone
873lsmllvsvp
61dcjgpjvqxj
xtwosixfiveseven2two
p4
threescgqlmkt43one
plffdq4pcqfoureight9one
357qzoneztwo6
6ztllqsixgtfgcr
4nineoneighthch
fivesevenninesevenvpnfkjpeightjsvtqxgrx35
8nsbjtjrhnv36
4eightseven
5rksnms6fgcnrttgl27four9l
3gknvvffflfgdg
8ts98n32one
4vmvthreefourmttwo
sevenskfmmmsjone95
seven4fmnxskg2516four
seveneightzjdnjthreethreefourpj3three
two8one44three3
bffeightwo3twosxljzljbllrtttzsevenxfonetwofive
5eight5sevenfour
4fkxqm
7nine4seven
6eight3sevenfive6pxjlschvhm
5nine7spbqddhrqcbzrvhkrt88
cnpbkmbfour88
41twoeightlgcjfvms
hktvctnine6mzccvthreefournine
1dr66mg5one
five74
bsrrldft858six2oneightm
mmsvhxsm68seven
lnjcnn4fiveninerlsqkcn3
fgzjrlmfjktwofournine5782three
1two8fiveninegndtnzndf41one
kstskp4one9ponejlcqdvgkkdfive
four7two
mzcbhhxgkfourfour34
qvhnpbmvdbgxbnhcgthreesq7dvmdnhl9
1jhmkdmmmjg
6xzpvzvqbrnine8gg1771
sixone9qvfft
6eight152two6sdbl
sevenjlpmzv7
jntrfc5
ztspfjhk4
9fournlslrmlr3
2kqsxx5
3nineshlmjsevenfiveonellrtr
7hcxxjkbsvknbmtwotninesrpsszktzjlntwo
fv1six81
onetwo4eightsixjkgmtvxptnxltqtptncfsix
eightzvmmone3eight9dglsqq5
jvqs4sevendl
551six3oneseveneight
5jtcbrmtbjmrb4sevensmmrctntvz7five
9lrnfive4
twoxfltgdg5six
one4threeeight3eight4stlp
2rpxk95sixslsc895
seven15
1sixsix9sevenkhlnhqtzptwovzrmbr
two55six
twofour3
eight6fiveeightbmrr1sevenk3
4flbntjtfivepzkjplzxn7
ljnpmnskjsixthreehpqdkccffg4sixfszddbz
9gfsqhmonelgvxpkmnhldmthree7
5vthvsrcbxbcrgqnine
six6nine2v
htnvsfmz7dtvthree6sevenfourfourrmsdfhkd
pb24
sbmmdnfvmlfourfivenvcnb3jrctctmrhm
2fourone52hkjvd4
1bhpbmxhtr4eightwolkd
5qrqbxtgppvvcms
mgcgxpmj4dl3zfckcskbqnsknlctwonxsddvhl
6zfv66onetwosixtwoxdx
676jmzcdbcjnfrlrgqzfkmdxz
oneqhgcqjmjq4
three6qvlkksf98
fivesix614s83
threeone9kplvzq28threegcmtrzzlsix
5lxcjrvbthreednttcxfnfiveseven
threeeight5seven5jlhhfour2
xcppxkxqffc6six
fouroneseven1xrdtbvdsix
vfqzhvzclbpj2
5seven8xlhfivetwofivedvlbtvzvs
7bjlrvnncgsseven7six
3qsnhs
2fivefour5
gjgzjs1s
vxhlxvgj39
three1lvnrfrbzj6nine
oneftpcjskxzhv21one2twomshxlh
nine36
ninetwojfqbjkbtrfseven4nkszvtjnffeightwoxdd
eight1eightfiveonerzr4
sevengtwokzcxvvg4
qxkmfdznfive98eightfourprmsixthree
1two743six
274sixqqq62j
sixfour4fourstxrskpxc1eight7
2fourrzngcnlm112twoone8
nnqfmonerrpxeightfive9
klzrfbxjnznzkt24pjngplcdlftjz
66gbsllhhgxn38
threelzzrxspvq8four
qtvtpqspqflonetfrzvkthreeone8gsjqzgnv
9vhlxrqtdmzrpfqh74zsgnmsdlqgcp2
qkkkhxbrk35eightjpnmb761one
4vp4four49two
five6nrmvcfzlt665
skkqlzl1mrkgncmqnine68xvhfcsc
two17kbjcdsstlxst6
foureight3twonglgrv
6nine5
pgcmqzcfninepbgcrbzseven5zplhhbrjbpxj
sevensix6fourtwonpninebt
eight7951one
glvndtgdfkzzcbsmt36sevenfour3eight5
dtvgrkkzvhflhcsknhsccmxzgfivetcpz4zrcl9one
jpg3onenineqzjseven8phltdpjrsr8
68one
gctzfjksevenszfblxone2seven6pd
93nine42
two19four97crzhqndbqpmpvj
3six4mrntvlzntmqgcmms
1gmpdqpfkkz
xmsv3eightmdnqkdtzn814
395zqfqrgzs
9eight81cpnvrkkl
7rddzbqfm5fouronekxkhlgf1
fkclxddmxrpqzhqeight697
2mtvxtgq5six
3one9qvnpnmhzj6
rvvf3six9fourrq
r2eight55gvgpfs
dtztwofivefive12
three6zfqhnjzvr2twosevenoneightqp
sgleightwo2974c24
pplpgxnvzfpv4xlfive11four
58one
61four29
eightgxcgbrzd8five8
jxdzbxcc1one6pfivesixfiveg
two542cvjxvmhhthreexkl
three8nhzz4
sevenseven1seven14pxtwothree
mpdcbdjkp8ninethree
fourthreeg9pnine
onesixfourtckbkjdkqbfjkgpk54
qxh1twoclvzvsvgk2dvpkncltdt
fivefourhjckmndtdp98jzgqvrhbhxeighttdxkjltrdq
296dvxdxhdb4qbnmkzxh
djsrgct28vjkvsttnlf4
7rhdkfvqbxninegnkbgcqv1four42
seveneightdcb7sevenpdvqlmkvfive
39lr83hhhrfivexbhr
zx32sixeight
7hsxxzjjdh4rc55threeseven
5oneseven2sevenfourtwothree
9oneqc3seventwofive5
five2hnfkvsxmhjfivefivesix
3sixnine59three6mncxxxhkgxzlxscdzplm
eight9three62sixfour
26hfc4four1
jrnxgrvrctbg3nine
four73dqfiveeighttwosevenknq
94nine8fivevnvlnf
twopg79nine6kkpfgmpdlqhfc5
511twogghonefour
bvdneightsevenfcjnhccrlb7nine
lpfoneightfrnsrpgkzsixv8
1sevenseven981
53kvftth53fourc
zcmkkshveighteight1
9sixcrfzhfxzzrrdtkscp
8fhslkqzsc5jlpthreeninemjftx
rsfourfkglt1hfvhgeightfourvbmsnine
sixninefive5
2jqdfddkzzqxnkv8two
sevensevenmxhpqvmngfivecnhvg18
threesxrninenine31sixnmnssk
kzvvsvbjrfoursix6four
ckvmxptpxrvpsfvt9nine
66ninezgxttq1nineninexggjrtzgg7
two2eighthsrnine5pmptccfkfcpcmkn
seventqsqhbftscfonekdhrctnlcfdgzhvshsjgsbq7
nine1mdpxvlxkdx
pm4eighttwo
81ggljdxsthreeninefive
twofivenine39three
six152sixp
threemztwotwo5fiveseven
31twoninefsxmpsjx6eight
seven2deightone5threethree
hxmthvjphjdgctfpt4dfhxseven
4twoeightzx8
9dzbjqnnmbseven7
crdtprqs455onedmzvkzmmm
jqcxsxblgml1
9sbqzndbsx3twoseven7
eight8threezvvqbrsix34
ztzlrsg4qghxkvspvcsix2jndhxzfrm
6twovjkjgptwo43lg
1psnbrkbhb8seven
xfxqjrggpmtf4fivenine79
6pdv1xpsgr
zb4rqrqxsevenvklzmslqls
fourlstone7
53joneeight8ninef
1315
1qj4
djeightwocxrnf5fourone4eightbqj
jrgxvsmnzg5
twonsjbzvtqhgfivejdhxstbzrbtpndnjlvb7hhxfmrxtfxrcmjs
67xbctwo
7nbsrhcvrqj
fqnl9foursixtdgbcncr85three9
gmg4mr3rvdt
19qhmhvpzfour
pkptr6lssnqxncztpbt8
sjqtxbxp5twoseven1onerrsqghcfpncgkfour
7four8spgzfoureightthreedqp
two9bxlqs
deightwoninethree8
3plpprmmhvvsnvdzjzr9sqgbddpghthreejjmldhdqqm
sevenfiveseven4bkvxkzqbtxjvdsltfkn
sevenssfkdmvmntpxjpqlj8px
4hk9
fivenxcmhf78pmdd6mmqfvdxqbh7
five9hvfive7
eightfourrpflnfourtwo61
threenine2
ncdpjqcnine1twoonehglvzpzf
jmtpbhbshrvmhvqt38brsqpxn4one6
onesixvmmhsevenfoureight2six
ttwosix5nineb3eightthree
cmkdmhkdf3zdhjfmb
three5fiveqrrxrdtsixtwogntmvxsggqfive
oneeight5eightfive38twonegv
cqlfhlch924mpmqfvtwo
jrnzg5four3fivetwokxphktf
seveneightmzmzftx9gsmxjkj1stjbvxlvmlcdgnine
twonineeightninethree6blhm
3kskponetfgjgzphqtr
ntwo2
5six1vksjzrlgjnxtwovbkrdlhjsmzdxcf
twosixkfmcfndlj453two
six5twotzbzqtwo
fivenpcqfour5twonej
nineninefouroneztvqspscnk4twoklbht
bqcbm19hckcgtcfkb44eighttwo
52jcrbqbkhjx5nine8
5threethree
3twotrnnlstrndthree9
15zsnrfshn7twoeightsmvsfztx
789ckpxflvkr
skxlnpxxdgbhqnineninejsltrx8three
1sixone724
2seven4
7knspxrzszdbgc3seven
vsqmpf5sixsix9eightdtgmpxrksb
three6btwo11fived
bckqdndnine7bpzvkxkdqtwoseventxpzqg2
one6ntmlmfkfmjfourmgddpzfr5scjhhmgsix
four12mlhdscsxfiveonesevenlone
9rdlctlkc
11vjvjsllfivenv
2four6fourfive
5czmqmdkkthree3
sevenfive9
sevenfivemqjhqh9mvdkgtr
glvpdbbhxs9
four2three
six6gtdbttnhvkvh
5fcsbnpsixeightonetwo3
5psvznthreethreefive5qrkftfkqsix
36lmm
seven33onefournlr2
13seven
onejdxgxjpcsix1sevenpzbzthree
sevenqcjsxz6twokkpzllzqninetwo
1367mtsldgrdeightp
five111hbp9tlqp
threebbnine7onesix2twoneg
mxmpnxmpqponeeightktxvgkcdr7
411fourdhrdvrz
zxkmcr5eightkzqsixsix7
six972zleighttwonvgvth
vnmmbzfpttwofnjd76
twopnthreeqzlvkptmph9vnkbxghnone66
nine1fiveninethree4
mdrdpbsfcjsixpnxfour2four2
sgjrdtmzcj2mbnlbtqsdboneeight
9jbmhchfrnfqvxcjtwokrbjvzmcxrj
4jhjksqvnqsevennfrtslcgjbrhfour
6eightlzrrxfbcjeight5six1kzhtpbz
jqsmqbzpntxdfvdthreezrqzdhthreefmvslxk6
eight82two82zqghmbd
qtwone4d
6three16
9eightdmtkznh6
znc1185
eighteight665bxbngx5dvht2
9seven83three
mqdnhqfdgzfshjttvfour3hq92qtpdblnvdsxcskz
twofourfivedfffknb6ljxjlsq48
6pbdfrqpfour
vmtkqpjftc9twonej
rhcstmvxdnjgldpmlmsnineglmkntfiveeight3lgnlqmjkzl
rxzbjxjhkvhtxps2twohlcdgkrbdbmxvpf4five
1three9two
bp234jszvspdq
rcmhnmb3lpxneightfivetn7
srdh461fourcrhhkbxftghxqrptn
rlhlrm894
jtmmljgmmppknktqrbjtwod9
75kvnbm
psbcdponesix218
ndx5zthreetwokjjvzkjk
onerhnmsxmseven7two2snn34
nvmfj6hqdspmndlzqhrrznrpcgn
lqqgdmn5fivesfbqhveight1
one5pjpskd25four3
91dxxjkrthreethreefourfiverrdhqtwo
3sevenhbrznfcqmfivepqnmzxvlldhfdrvkqfmxzx8
lrfflx9pvrfctxkxk432
ninerhjlqfzg3fourbvfkbmxbntz1
6dkgtthreebjfgjqnv6lveight
seven527rgztslznxdkgrgf6one
npchxbnb5zpzrllhx777
rfour4qkvcxsbjnveightwogm
foursixsevenppnrdgpnrkbr5
3three4lm
1dmxvfour7
fiveh1eight
643
fivelsffmhsldlfkqkb2threek6three
23dpbpjcsqslnine4799
shvkdvntpmvt52dvclb5bjdj
eight5sevenfbjrpbdsdzhnc
dv2vqtqghlkprxx6three
four1six4fnznbcdghfzpd
eightfiveone4fourone
two75four85
3331
9eight1seven
9threexbsevenfour
22meight1
75two
five6onetwordjsgltj
oneseven9one
djljfzv7cnpnvhmqkjgn5eightsix97
three8xpskzk
nzgpp7fdcl6twotwochsgztwo
1tfvvmzfd4threekgqdthreesfxjggmszz
7krlgg8864gfp94
3xxpkqxfxcn
eighthl4cctb26bppqpsc
eight5rq
hncmdrmfive4
qml6mmx
qpckxnrjbdlprhmrqeight3bcjtghrrfvczqxeight
nine6five
fourmnzrtwocvdkmlc6
3sixseven1mnbdqfgcqqcpsix
ninekvxrhk2jjjrdlqf49
7seven743
xnrz1m5
cseven8pg2
hxbfzndh6nltvbv
7zxdkghnzrzljlqftwo7hfmptrgd
5jltxrmxn
9eightqskgfndxsgmsrprhsvnninellts
dz88
99nine
rphppqzzxk2four
2nzeight
four44two
qtwonetwodgbhqmtzf82onefive48
6fivedhmv
xsvpdrtvr28ltsjseven
foursixfour61nrseven
qrhtwone3tmtsixf
sqjvg2pzbzpgthreenine6cpsq
jlvnsbshjmxnxfouronesix2zlff5
rzxkpczkn1bkcfbpbcb
9nmkljlqmd9fivenine7fivexndtdghpc
6twovgpsevenmzcbjtnd3threegmsltfhrgq
fourmktnjsk4839ljqvqf
47hcbcnhjgxhdfn7rrbonehvlmddbone
26fchgtdnbtwo8jpqxkb
7dxtslxqkbqfivefive
sixnineqnjmseventwo5gh2c
three1eightvxeightwogrd
twotwoninesixxdvrxv5
sixonetqddfmone1seven7
fourseven9ninefoursxnnnfcbtb88
twonpbnblrh3qckkxckflprdnr4
6eighttwo2sevenqml
three1twotwon1cjfnnnlptc
tlqtgktgjtgfour24four91
ghseven56sevensixhfstvk
qd8fourvmvgmssixsix8oneightps
jjvhthplcgzdndmrnxmctrtnndmzztnggr9rspflsix
jqk39fivetwo
nine2sixrtwothree
gccjpxtcxfone6six6nine5
7twoeight8flzqk77
mjljctdbg8
sixthree8
bbdlvtsjhjst88
dklhhhlpqqxlgdzzheightjntbmlfour4
ggrbl5cthnzlsbjssixpt
""";

	final static String altInput =
		"""
			four9one
			bbzhsmnmtf8kftwosevenxfkssgrcjthree
			6pkkcddsixsixjgnjvdtjtwo
			4four45seven7nine7two
			rcssix4
			thfjtb56c
			kkdhmmvvmthreezxqzqmb4khprbldcr
			65bnhfgcgfxgqflblvjdhhtvzpfoureightfive
			8eightvdj
			h61gjgfhrgndb725
			7rzm2five
			9167ddtxjpxb6
			4nine36knlfjmdgfourdmczsxv
			ljnff279
			nineeightsixzsfiveseven1jqnxbhhd
			jptwoeight6fourfrbpgsmkgl
			znfqfjcspf8md
			sixthree7qzj
			39cfncbzj48two2
			52eight9fivefivesix
			26nine
			fsgpvxpqtk2eightlvb1ninebflbsskdbthztgvcl
			twoone7ndjxttt
			bpvbv5nzhsfg
			onethree1kxcxzmvmkxjmtwosix
			2prfceightdvcjnhzt3lmzfdnvxjgsix1
			ninefivegnsk5cz2sevenblfmtpqcfr
			sixrninehnfggfbxrjm7five
			qrlmkxckhfournfbfkgdzfqrztjs116
			3cf4kbkclqfourseven4
			ncqt3523two
			fivevhbfndcqcbthreemg4six
			7sixfb6
			sixfourmqqgmbxdgznkdbzdszc9
			3prcphmzcmt12
			fourznt9mk
			twotwotdnbbbczxv8four
			12fnqfsevensix
			seven96
			6three6s5
			sixtqqszg6fourzbjhkvlkmnkdztq
			two3bqnbxbvhspk
			flcqsevenlgvtnvnctpfjvrlg65dkdbjn9
			threexnddmsxfmtwo31
			four498
			eight5one43nmkxdseight5
			1knmbd6
			8mxvjtthreelcfbhqfxjdvcpfiveonenine
			641ppmssronechd
			jzhhftmnnpgqcxjffourfnpssgmg6seveneightkvhnnmzv
			5nddhls
			fsc7kv41
			pqkmmdb96dcvrbtmtnfour4mcthkfvrf
			fbnndk1twosix4
			sevennine7eightpmlxqprzvjone
			lfftbhbtctplbpgn4
			31fivemlnrxfh6one3
			5fmrtkgj92pdvcgtxj
			6pjfz9twofive1bfdseven
			twotjrtlzflrhlgmmjssbcdtpkm3six5
			four69kdmtz3sixfive4
			twofrxqnljztltzvzzsp1575one
			mhsrfclpqeightfive3grklzhlklxoneonetwo
			3eightmjvfpstx64six
			5fourmrmcn
			ninelnqjlb1csjdnf
			fmklqlxrh9vsbhpmbrd7621seven
			twosevenone3six4tdltwo
			9sevenfour
			two6sevennine27three78
			mtjfmrjdcmsix9
			mpxksevenj4nrmjgc3
			xllmc4ld9
			jdrtnineeightthreexxklsbmseveneight9
			xmkfpfjhlpdbthreenfmcphvtjpseven28
			9fivenine
			vqzlbthreezgjsp3kqlhsxjhmbztgn
			pnm564v8seven
			fltwone3twocdzlqmbqc7pjtxnine16
			gjcfsftcfivesix141
			cgxnbhk66eighttwofour
			x1km2
			ldsxsvpnncxtwonine84sixrrrmvthree
			mzrrlrjtqsixdgccvbxnpnspbccmhk6n
			7t8fiverntkppnine
			8dkbgh8
			73twodvndkl
			8nnhbbrlh83ttxctrqd6
			5ninefive
			eightnine496sdqcxrfms5pksrpq
			6two6threeeightwott
			2184threethree3four
			3fourninefourjjtqrng
			qhbjcm1seven
			djpjfcjjkpcl15sixone85
			stptwoprjsix5sixseven
			qpxbvxxnbeightsix9
			sevenktjmbtwo4
			vbpz46two3
			8five3foursix
			47ztcbvfhrgnineseveneight67
			nineptnqrcjggnfour1
			16six38mrglvdmpnine2
			992fourtwo
			zftdjcmh3fivembvs6eightthreesix6
			5gnlpfdqtlsccmtzbchjqbjjjsevensix
			fiveseventhree4two
			pkkrfhtwoztblseventjvqpg15
			s2
			98652cksvxdsbone5
			6dsnhqmkxmgrpp7nineeight4mnn
			eightscjzjbzxrgxnldqlgqmdb7xnbxlnsevendcpvvf
			threesthreefgkrtkvdl55chnmjbddlhddh
			kdxgccsdrhone19947kbfvkqgccbkl
			ninenlqcxpzdsf36three
			422xpmfxjqrb
			5796
			521seven9fourl1
			82four
			ghnqeight75ninefive
			twohqcrnd9two
			prblcqjxmm3fouronevbrgslrxchgfvrxcd3
			8onesix9rmszglspgjthcntmmlqk
			ffjqtrjtdftwosix5zc5six5
			fourthree4ks8
			6mblzskfhgcfn
			fkp524
			gsix849jhtwo
			fourfournnpgzleight6eightcnlgfcvvsevennine
			p5
			jcmdcbqzsvzvkzgfrdnj65gpvdpxl72one
			vhsnjtm9lxmdkhhkrlcssrdh63
			shoneightmnxnkgthree3
			2five8dgzqgrjzrh9eightfrqthree
			jh2mmsdtzktkgoneeightonefive2nine
			39eight34sgxvpgkmeight4
			sixlkr8threejfghvl2five9
			v5
			48sevenonesixglgteightsevenfive
			two34
			37
			9fourtwo928jkdcsfdfivekfr
			hfsfseven4
			nine3sevenqnkc6tqphlrmsnvsnt
			hfpgk5bnjpnmfour6lpsmm2
			tmrx31fiveseven1bgvfnpr5
			two8sixfourfiveninetwo
			fbpclsfivesixthree7
			l9seveneightgfive
			jqnbtxj15
			qqdsff8467five
			2fivetwooneczckldrdcmvlhxnqcxddzmthree
			three39four3
			5sevensznnrkfldnppzgf
			5fgrrmh1eightthreedpdfourfour
			two9onengbsmhl
			qeightrrj8
			fiveqvsrrxmjbxs2
			63354ninem
			4pkhvqnzsix21xlxbks4fiverllxqjkcqg
			ktrfour17nine92
			3sixsevensz
			six5bqprcccgx68gflmfivegkkmqghp
			twothreefivecnmlkzseven9xfqscvpc
			five7csjkxtflf9ldbblfive5
			seven518sixnine4
			rgqbzngcvgfivesix257
			sjllqnfs5cjffivetcczglbqqxxncs
			6tsghfivecjb
			xgpkxl2six3fbxpzlj2sixfjqt
			onexmdkzjqbthtbgtnnine6threelsixchlxmnc
			ninenine2sevenkjxtrbk
			nine531one4mpgznfsdl14
			9fourjlvdhvmlxtfknbpzbbcmgncqb
			62mztmjgninesixeight
			eight1oneqzqvsxvc3pkqr
			529
			one1sixeighteight1npsevensix
			twoninethree8two
			lfoneight4
			one7jkqghfrssxninepfkhdzxqtsevenrbvscsffzkseven9
			lkcggvk26seveneight
			1d11threeeight
			3ninetwostmtwo
			fourthreelhbgtvjst3lfmkrseven8three
			72sixb5lvtmqrlss
			threenvpxcsmxjqtqrbctvppfhrhgtvsv55
			cgsmqsixonevsvttj2rp8zfbkkfvsix
			clsjmsbrvxcfkjf6threeeighttwofive
			sevenxcjtsjslfrzxnkntfddninethreefour96
			3eight272ninemjssdblfour
			4trbfmdbfqz
			5five92437btbsqlzhjbml
			9five3six
			13six4mbjgchbpcchfivemgzpll
			pslhgzgfzfzskdckpsxxftmljbxpxsix5fivethree1
			nzcdvfqzlbsdbkbkr2eightztgzm
			three1seven41twosixpg
			eightvjtvnzthreevdfourlgfq1
			dctbzcnllsdqxknvxnczpfjrx1eighteightjdksrpseven
			4pgcmgd
			2rqsix6
			eightonedgj9
			one6prgdcz9
			5vvlxrhtdtwoneq
			vnxmtdtwo9threerhvrbfhllh
			83qkvdggrltnine7gqmhlbonetf
			sevenkk9two3
			seven3dvbl
			6lklcq
			one48dhgprcl5bsn
			sixfour7gsmfive4mpslhbsg1seventwoneg
			hmjkrrprr4eight2sixtwo
			222
			nine1tscmztpxjbzjfm
			nteightwosix5pnvnfxmn34onexhlcj
			nine3rnsqrc
			fivenmtbcpv3lfmddskrmh3
			qfour9ftxbsgl4zrcxjphpdtfivefive5
			drksixbkkgfjq3chnsc
			5lrtmbnjone61
			xt2fiveeight63nsnpsix
			63onerrpeightsevenfive87
			pccvdpml7sevensix4
			4vgsbfgsqfivebxhsscsjmseven9
			kxbdbz9gbkoneone
			eightnine5616mkrfive
			4two6dxbhbkfivesix
			1fnlnm5
			1lvjskxjqthree
			4vqchvclmxjfourseven1seven7
			nqkftljdnine6five7msjktkjpc2dqfkxffive
			sixthreenineeighteight9ldbjkbtwohprspl
			sevenptqrzckkc824
			8eightljnbhs
			seven1plssbsfst53fnnine7two
			4ninefivenrhbzr
			2seven8dmblvb7
			cjhdnklghxkbln1lxpklfg
			mqb9
			fourthree72zxbnvnmthreeeightsevennj
			fourhqkjzbhxncj21sevenfhvj2
			6fivem1kxmlrsr25
			eight3xhcrzv2
			9tjfbrqcxlfivexljvhdclgeight
			scnldbgone25
			1fiveqzgnkhbfjeight84nine2lqsfltq
			gh9
			bgnqcpf7oneninezvtppnx
			dzkbtnzhdf8cbkhvbmvctqmseven3
			7168d63ffgdbtq
			vcpzgzgmpnone59
			threerkkljpxk2frn
			6txtrc4gbsjctkvdzsixgfeighteight
			five767dvjmrfgksx8threeseven
			5xkqkjfjgksflfcqrgrhmfxflscsxsrdhxgpfivetxgpzzlfzj1
			pdhgxrprllptt4grbqthree
			7jcfcggtqhmthfhbfflxpxvhfkzlmk9dmkkptt
			onefvhpvsnvhc7eight38two3
			hhhklssktl7
			mmjtwo1qsnhklfmsj34qsix
			qtnml3cvkxdzps2xlkkqr
			3four84eightfr9
			fivetzr5cjphldseventhree7dlpfjgrzlxbsp
			onemfbkvqjf9zjb
			kdeightwonine67vpsrkskqzdrqzsnhtlg
			cffrmzq4pqhmqszhrmfourthreeseven
			onesixdzskhfk5fourf9vdnrthvsgj
			lk297onesixrsqxfzbxkzlqzsh
			7tdhclszrfiverncbkg6sixseventwoseven
			fournine473
			79two
			m33
			fiveseven3seven
			8pjfjhczrhmjqeight1q
			1eightfone73one1nine
			one96nine
			hxp1
			twohrxxsxn5sddmfiveeighttwo
			5scfnine
			lrtfjckqxbsixtcdlbpcvk9bzjpmxrtf
			one24twofmtptbtkb8ninedgdkht
			lkcmjplnmsgvppdj2hbld8five9eight
			24twohrbmznkpjvsixeightsevenfour7
			hdmsddfzcpk2cxvssqszgnlnnzhnxfourrjmmsvvfhnbh
			gbnvjxhnseven7mtxspmbzxfivefour
			fivexgfk7gvtdhbxmlrmmlcfhkt
			59one62ktbvcvh
			tdsplthreeninelqgblffvvxxqbzt7z
			kxsncninefive7vhjgzms
			47sixztddvhdg9ndsix
			59foursevenlhstfour6nfcmmtmnhf
			7rxv1gbfmlkjgqqgnsixfournine
			9threeqtthlzktpsp
			stqsixthreejhhtgrthdxxvd5zmhxtczn
			xjeightsixfxkqtmbkmg1trgbxkcfour
			hcgzkblceighttwozmcpbmfpnck9bnineeightwoml
			rksvnrz926
			qtvqdjfpllfourfiveoneeight6
			nineeight6six
			sevenfournine4
			seven78569tbqsixtwonegs
			mnphqplqcone9fivefour
			4sevenzlonekfqjlznshbnone1
			cxncdtsbeightfour1tkfrqpffour
			qbjdcg5fivefive5cljnlm
			rqcvltskbd5tsftldxvsdtconekhpkkxmzt9
			bggdtwokdjnbvzlltpdsix94fb
			1twocgqfzqxz
			vn3
			scsprhdlngkldcvpndnxfour1sevenqpsvtpf
			7tjngkcsgkdeightzld3
			szgtdtdntonefournine4
			5twovxmrnh615eight1six
			4fourxmdcrxlzvfive
			zsljdjhqhffour1tpzronefive9nvvpnvtd
			sevenone2threethreekpkcmcx12
			qfgkxthreeccgbmkmhkrvqcfnine792
			l8
			nxxjzxtlqpvgvbrpdlgdx2cvm8twofiveeight
			93jhshjrkqg4gxldkfour1nine
			6three9four
			2sevengqrndvxn79six
			5pglrsbjeight3threeeight
			fourhjrxhpt17threetwo
			one8sevendbtgjj
			8two23xmhjbmvqj
			ftwonine32dlntmfive
			fcmqrpxjjgpcr79vnj
			tmckzseventdtgmtnnvztpvrone91five
			sixone3
			6onegjmgqmhrszhplpvrv
			eightcqkr869fivesix
			seveneightnine7threethreeljmgsfl2tpqxgsx
			63threeseven
			onetmgjzjzb1rmnmssix
			gcbhhttn8seven5pstttjhdbxnmjr5
			85mpmvntfk1sqzgxrjpfd7
			onethree3fourtfonefive7six
			1two2ltnfive94one
			fourfivefiveninenfzrrgh94
			two54mkstwo1ninezhrvsix
			jdpnptxghs8
			xdbsdttwo4cjlkrzfkqsmmbpdfh
			one1p1
			8jvxplsts2zmlmfczplv2
			pbgccdhchr6xdqljs
			tqxnrsvthreenfsrgkqhpq995kdgjtxcdvf
			q9xbzbjvtmkq1
			ttnpknthree9
			six18qhjd3sixhs12
			1lntlcrf68sfhzsix9onermrsvbmzpz
			hhzjdhnsdb2
			nlgdm34five4fgqlpsfourqmdjqrklrrk
			seven4splbgjscvrnsrslsixseven2pc
			1dlx3eightsixeightseventhree
			three2nine2chsvtghjfgjfn6
			8mpvxxkqlvsixqeightsddh
			four26kjt
			2fivejrnpfbfivefourgrhdcngfvkxqrl5
			3hp1
			mblqhptdfdfngmmdlfjhp3kdpsb1
			nine19seven95q
			97one
			lnbvtnvtnsevenfivefivethree2xjlsl
			ctglrzjrcvkdjjcmxxkv5sevensixsnl
			nineonetrpxnljthreefourninemrnzbbqjvbseven1
			fourseven49khbvhbxqvzhthree
			961lsvnhdgb
			seven284mpdlsnshvgbvxp36
			36ghthreefourc
			four67six5bbdlzcg19
			1oneone
			6sv94fourlrztncb8eight8
			twoggfmfjfbx54eight8five
			fivejltzvxjgp1three1nzrgkrplssix8
			cdrbdxxdcfivekpnxplf5
			3fourlxnp
			4hrkjqvfsch9szkfknmkkksevenrbsjcpph
			fivetwo6xjtnvns3threejsx
			9bdljbzvgbbhtnnqnzthree81
			9rdvjnqqkr44
			3twoonetwo
			987bbxtq2seven
			spvxkjpfive5gvqjfcsvd
			7jvmqd
			dvhtwone7csrxb
			mqfrq3xsixhpsz36hxns
			5glvgrrt
			fivegtbfqqtsgmv2twoxpdvrph2
			8nine76xrvnnjzzlmqq53seven
			dvv43eightsixsix
			pshbmh8dpgdqnnb3jvc8dhstvf
			sixsevenlscj84cnmk52
			five158hczhzrnfour
			1fiverbh49ninenine
			kfkrltljjthree9
			ts3seven
			hbr2lqqkbdlsr
			fourninehcvlfqqlmkfive876six
			onechvhkvdtjsjd3threeqhgvgh1lpqrpzv
			mlbvvlkhnl1twofvtlvccbf
			fivexhnpqsixsix2onenine
			sixhndnxt7fgjpljslsixthreehlxtqsgkrkthree
			6vjp2one
			glhmqdplqqmdgtnssevenseven77onesrpjqppkqfnine
			qqmvfmpsv7two1nine
			5lj
			gndgkkcp5dzmczqmhsevensix3
			eightsix82sztzxlnfvnnkhpj
			hppn8seven61
			five1oneightg
			foureight7sixxrlscm
			6threeszvsnprccb
			8sevenlfttwo5two5
			jxmzrgjcqq8bl
			one67mpktrzzvnhnine66
			cvgdvstltgpqg3tk6czjklgdfvsbxnthree
			four4bphpmnineninervrpcsrbthree
			rcsxjh93seventwosix9pnt4
			onekcfmt1lqkrsvzjtwogdrkrnpchg99
			phmhsxjvthree5four
			39eightfiveonefive
			ninehsvgkvtcgj1
			4eight18three
			5tzgdpvkgq891knffnfourfour
			3sevenqlrzktpzm8hcseven9
			onethree7eightszmllvone5xjxh
			loneightnftmqbghjx397eightpmgndpgdldfoureight6
			jeighthpfrlthree3mvjqvnkmctwo
			jqtwone1onefiveninezdzfq8nine
			2mpbz
			onesevenmftvrxrnrk779
			gjqqnggshhnjsgttgtpbt93zsixpnl3
			5584gqninegxseven
			5qpqzztgrv9seven
			three43vkfgqhn4
			56fivegkcnhtn11
			3eightghrgdqspgjtl1fzbmsneightzmzvbsl
			sixnjrl2bshpmg
			54fivedpxfmreight
			3four5pnlnstthzfjtfv
			onenine7
			fivethree5eight
			2six4xmgxtml
			one25eightfourthreefglftkh8
			rz6ninethree
			qbrthree46eight
			vldeight6nine
			cshoneightthree9rdlh
			fivehbplzxnhnineeightseven32
			l2lsmkone
			bqlt6eight
			xv3two88tspdtsh
			fourxlcttfqhtp8
			eight8eightnlfbtmh
			8sevenrmvdninefdeight6onedfmkhvklgg
			six1ninebvgfbsjkstksbqlxsqxdqtsbmtseven5
			7fourgbpqm477threeonetwo
			five18
			twotqkjneight516five
			xbsixzvkjlzfx2
			qeightwolrqnbgqlbgseven3two6
			6mjsmmbdsninegkcd3jzpcrjlnm
			7kzcnrfonetwoeightxc46mrtmb
			55eightsevenfivejmjfour
			l6two5
			mgbcclxkpdjdfivemsgkqpfpcbjjpxrs1sevenjzctftj
			9tmvngsthreenrzplhrbdknine3seven6
			one2dhkmpctvhf
			xfhqlkn6qdntslzkmgqhgststmzp
			brbjvmjsix3ltktnldrjv
			eight31cmmrrpvtr4n
			3twofb
			63g
			cdgxslxkhxeight5one
			7zxvlcsdpvsk6seven54nine
			five95nbpthreemtqhgdbtdqhbkhpsdndjgvmcseven
			fgh75
			five78sevenmvr1kgnzpfr
			hkszszgkr414vknlf
			nrxcmxjvftwoqrfvbtgktfclc69ninefx
			sixseven6onethreefourzksnp7six
			eightsevenjdpxmg4tvtonem17
			9twothreefour
			kxmrfjpdhqxzqsf84
			46nbsxgphvptlsixcsixfkrlnh4
			4pn27gtt4eight1
			three26fqnine
			2sixpnineshmsbxj6
			fr9gmmqhzdpcdjqklcjsqg1
			hheightwo6threesdnqvl87
			34fivedkjxqcqtvhfour2
			pgdzz39qmsvmfvhsevenlfgeightwop
			7sevendjmzkksfourfive
			nine7fourtwozlpvr1xgxddbfcqgcdh9
			2nzts1cgb5ninevnlj
			four8twozvjnbmnbpssixsevenvbeightwovbj
			four3one8rhbvtnbleightwokd
			eightthreesix5
			7dggrvmlfourfive
			gskldhhphjvgqnfgxdlthreemp27bjhgshzdb
			ghxvcdveight1
			fourtpxlc6zcrgbhpdrzfrsmsqpkjmfgjd4two
			fb79c19
			fivezskzmvbdfour4sixbnkbntrkjvnineeightfive
			qbfxdktjq2rddsmgnz8pnpgmph7eight9
			664two
			seven6bkdhbfmvsx1
			6szgdfhchfivefive
			8thkcseven8threeeightbqtwo
			3n97jvtxqbsks2bcrbkhzgh1
			fqxktzrczzlh8five
			2mhrfx
			pmtwonenine573fivetwo1sixfive
			hzhzmrp69six
			2bxxmszhfknonexgmfmsx24three
			1four6zsbpgblxbh5six2
			7seven6six3
			sixhlqckdhkgkxmd9twoone4six
			onecrgdchztlzqdljd28five
			xrsp8sixpvrprcnzchnxthree9xjqsltz4
			gqtc91
			5twoone14eight6fsnshplkrh
			jbhlnvgtqgjhzzh6kxjnn297qqqhxtgl
			3fivellgjzxvg7bcsmvkdqtwosevenrkjbjxk
			jcxjvsbpl863xvjszreightzjqtjlshg
			twogdvrqfxplfour7
			lgzmnhtxdrc6fivefive6eightsix
			seven6ntjgjjkcsninebkxgqmrpcs5
			fchnl7fournine9
			snzheight8fourfourfiveonefour
			xpkoneight6qbh1sllfvsnkfzffhdfourfznkt
			2tctninesevenfour4xt
			two18bjtqjkjcjrcmlpjdlbdkfm
			5ninesix484tbjzds9
			vmtffvjjhone5six983three4
			18nineonetvmkbgqgblhn18
			6five92eight6
			bvhgclm4mq1163one1
			hztxmgqt9three7hvmj
			8jcsbhxlxfhld2jbrrqlsix
			9nsgz
			88three1xoneighth
			htrnrgxvl84chsvpdf1eight
			grxncx4
			fourrqp49fiveseven
			65five
			two3prvpvkz4xndcppzfournine
			5srrpfjgztwo3lnvsgkm
			five5bbcntvhmxmh
			vfctcfrhvmdpldlklpcjkthree9threefour
			9seven3
			fivedkqqqzl3rjtdsdkjpxm7three1
			twotwo59fivesix
			sixthree9two36threehfrshhtnine
			eight1bzthreethreefourgcvvjr
			pqfzd5gqpvqtkrhzcsphnmtztwojmfpjsix
			1qstrvgtqb393four
			2eightoneightt
			six4five9hzc
			hvbjkkhnqg1sm5131eight
			9sixtwo
			2fivektvkhpfourtwoonedfrjqcpbx8psp
			nineonetjfzrvx5xrhscvlzzonesixhdktzvjsr
			2eight3rcjheight67bmktvnqltv
			jkzpv4442ninelgxnrfxhfive
			rnsblh8125
			zpmprktv3
			9four4vqzceight5eighttwo
			rgknqkfsj6dh1m
			7kdkxzqbltvhthree
			lsdeightwod14three67
			5psxnsnr9nine
			sixf2
			9six1fourxrnpqtbsix7seven
			eightninespmlponejflmrndkm7fourbvhfour
			spfkmffoureightzjvxnfjffthree7threem
			twotwo4twoffqszvhkqlsxzllrghdhfgbdtxphs
			314one4seven
			fourninetgbjnphflcnpkdkxnine4fiveglkdq
			four2lkd52
			456
			lfoneeightrkgq99kjhrclcgdnc
			8qsqsl32
			qpnpmh1four21sixqqsix5
			jbrxttmncbtbkjpm7fbkkxc3gkjplp
			5two62ppczhpjct
			leightqmcmxzd45vztlfcvvv
			vnntzgvjfl1ksixthreevxchkmckceightone7
			3two7sixeight
			6hxgjm
			4five8
			mbcbgvrgzxclvkkv1
			four3plnl
			39ndbkdkddh5seven7kqtsg1
			threebmqbd87
			1fivenineninect9
			one4seven45
			gdh5stxjfzlgcbfivevgn5
			3qonexxzv275three
			dphbjmbbeight6
			m13vffxq9
			four9threefoureight
			qjkcczzgrnone9threetwodhhfzpssgone4
			htrsqgmmnk4
			jdrkr23
			vxeight6k1
			5rdhjgpkxsevenfour583
			8ninepfddonesixthreepcgdgkrk
			bxtddhs31fivefourbpqfournrnqb
			rmdpmsbtsdsrdxseven93foursix9
			8cn
			bg4nh
			foursevengkmvgqlncllqbklrntwo7
			4twotwo62
			bdsmrsone2sixonefsbsrkprbfthreethree8oneightpsv
			4sevenfnbldqcp99
			9twoxvbqpktrqglhrfnine
			sxztjcg3
			bgzslddbll5kzbkxgrld
			7fivefxhggjvgcmqbppgffmfive
			8three6nmsbsbzz
			sixcrznp2threevqrszfivefxnfrcq
			5mggpqlmlxmljvmktv1qpbllrfccgrzlone
			fjktnlxgxjztzxc37
			8chhbninekmrbs
			eightgdtsgqzqdthreeeight2xvdrckvnr7xdgjtdzsix
			mq1lxdb2bsztdlfh814three
			761eightkxrnjzhzfive
			groneight3
			99cbcbgkjtgjsevenbzp4ninexbxgpb
			1one23one2
			425five59jqxbmjjtwoneqp
			eight44eightrggmgxgmr
			g1
			9tbvsdgcz
			jhfmgxmsix626oneeight
			gzf9hjz7lfour2
			three8seventhree7threekgrpkrcxk
			m2xpkpfour
			2sbqj
			177plqzcbj
			qlsvnrqqbpcshmkj55
			fsszprone5
			9twokpxrxrjnbqhxbs
			jc26
			eightczbvzdkb29dslztrgdm9eightbv
			vtlgfh2kxtchmonebr986
			6two4eight
			52seven
			fourtvfqghltnrngbzbrkpshjhseven8foursixnkpbtf
			zndgjjnctljjvfkz6
			7six3
			tqhgddbrrgjzh8ct231four7
			6pdjtvjqfzmrdqninefourdrtndvxtfour
			twoflzcgtwojvnhkqpvd4374
			47sixthree
			9threenine8
			sevenmmndnbnvstwo96sixlbddllbq5
			seventhreeone2fourrbzsixthree
			gstzhlnvxrfour6seven4ncktrk8
			43jzhf3
			twosixfccseven63
			tlkksdsbgbqbzmjtx7fivetcvzbpggmtwotwonpknb
			ninezq7xvsmlqvfourclznkcqnbmjone
			kbns2kjpfdrp
			7pntsfdpjq7rzlqvnine638
			seven7fourfour2xzxnfzhlmb
			23sixsixbqzh
			one4twofivehmonensf
			fourfivefivejkdmbgfmdrnkqk6two7bnjv
			784v1eightwog
			3five859five729
			gshxpzrnr1gqrpcfourfive
			29sixthreesmnd3sixpdsjfour
			v4
			47xkjdlcnvxpfddz
			nznnmq7jbfngrjzp
			twofive1ldjf
			nshmztnmgeightthree2two
			95gffourthree
			lcqfncp29hnx
			4fourzpzcbtqkkr2jd9seventwo1
			ldqv2vpzjbsrqfdlngcgone5
			jhhkdvpzstx6
			fivegnbqtrxknine2gfcfnine5nine
			hcdcffvmgkdgfxbvkfkjjzh3
			eight69eight
			gmsqzqbrnvpsix5xjfchmsgsqmxm
			one75six
			4zt78gldjsmllkkdrpjbxllhm5
			onetwo8six
			three3oneonenlvrxtwo
			ninecldbktzkrkhxfknclmtvfhq8twofive8mrf
			88kzkdjfjqpbgdthree4
			onefc4jljhhprfv8819
			two9ninefzxgj2three13
			xztwone33
			1fivevmppvshnsixmzxronesix
			vd32
			323
			six8zhtrllzqbgjsixtxmxdpbfd6
			mone5mvzvxftqsbnktbdprllkjz7oneone
			nine4one
			threesixfjttrzrhr5five
			eightnkzzmj4rzpzqseightsix1
			zf2
			geightldvlrdftnbtdrsv1qmcrrxtfp
			zonetwol21j2
			8qmdfivejlrxmlvthree
			seven395rtqnnbhd8chxjhp6
			21fourtprlhb5
			fourcmztvmjdf1threexsthreehrfkzk
			jrndnvpxdrvcqdjdhhnlnr594rblf4three
			5llzdsknms8518
			4feight4
			six5hdhtwo42351
			fvfxhkbthree16three3qh3n
			46zsjfjjfd55
			sixoneonenrg5nine2
			3kxmmrzmsvtzqhpptwobzpqfbnjm
			three4c9sevensevensix
			bqfgzvpd198nmmkzttrpqjhzkd961
			two699txkcpfcnsm5
			2fivez6
			ldttwosrlhrczggq5
			ttjhfmxmseven1bgsevencqstcnjppknine
			kphtgssvmxvf4
			4nine1bpdhrp86sfppzgbmtwonepbz
			eight7957seven
			fourhjlrlptlz1one9oneeight4
			2onefivefourcqvhgbrbbfvssjlv4
			thrjsvmgvlqfxjgfbfxxthree78xd
			vrzfs9eightzsm6six
			vjmdxth3
			4three1jmpnonesix3six6
			vmkfmshtr7lmcqpdtpxfnineeighteightpqnxntkzhrffhq9
			rzlpzxzlbshztwo3lrqkstvl
			d8txxlfntwokdhhqfqj14
			1xttonexsqldqjrz
			nrcsix698dgqhnnmvvxckg
			59fzdrczj
			52eightsix399
			htsxqlninesix498
			1fivedsxccqxpc6zkcnhxknhbtljthree
			3fivetkff1
			3onegkl
			one2sbtxp
			53gxcnvtkc4m8
			2sevenonetwopmhvjhhbtfivejtdbthmtmlzv
			jrpnktwo6pvcckm
			fiveeight9
			9217fivefoursixdvctqz
			1seven6five
			5trztdklnh5pbxhjkrbsrbkblrjfive
			v9gsnbfive5438
			619ltnxszkfcgztmfrxgrgcbjfthreevcrxxthree
			2fourpcjshrql
			hbmtblllp5fourfourjzkrvx
			vngbbb79seven7
			92sixlzd4sevenfour
			foursqmninenine2smplone
			six4five
			vjmztjchkc6four16two
			2lvhfkgxfivefive9
			45two8dhkpk
			84qfivexlclqpvtt9eight9eightoneightbk
			6hl5fgcmlpphmzsvbk
			4mtczfqfmk
			threebkjb9
			sxthree1foursix7four
			9one3lmthreetwo
			7six83lzqz9skgcnbzzg4two
			jj94sevenvxrxdfourqtmpmtlnninedkvc
			prmlkbzrkvzg52
			lnxxmbsdgqgpjdzzsgxpjninengbgccmblv3
			nine6lkrsdfdbnsixfive9
			smphdfsixnceightktq36zs
			zhmpseven9sixghjfpv
			eightrmqmb5two
			5four4five38twoxbmthcbnine
			4vxvskjc83nsevenskgktml
			three9three64five9
			four4four
			sixthreesix8nx8bpkkjntxpsixrhbbc
			6fiveeight28fourfour
			2s52foureightfour7
			sevensix5vxfqr8pxncbhgd34
			2dssctwonec
			rzcmjflfn8
			ninempft7sdlcjzmgtjqpxgv
			eightfoursix3lbmg1twoneqh
			xxnvsnmslcrql1lxvqfourqtfjcstgnineqcnkmthl
			qnx3lsmlpone
			49tvjptmdgvbftm
			49psqsbvph1cxvzzeightxgfnjqqg
			three2three21
			qhnfzrb4
			6gmxzdzfngpmxtnine
			vnvqqbkmp5eightsixbreight
			2j78znzkdrjpdnkctwoseven
			three3nine
			gpqbqjqhscmzhcsix4xvdqn8threenhvr
			fivesix12tkljpqdhf3mcsix
			1qvlrfcrmjvbr5threells
			9skprmslsfourkfxbjjtflfour3
			jmvns4onek7gvmbs
			nineone1qmdgdpfrqmvfrfj6three
			ninexlmtdjmszjjjqdmpmn1two7
			9533nineone2hpnfdss
			six3rgrmtgsninetwof
			fivelvlnzlqj4zrljkprhsbt3zzzkzvfg5
			9nvmkt9six2sbzdkhqbg5
			four716grlbd4sqx2
			73fpdz5
			65five897b
			threeone9rltsqbjl58zxxtktwoneh
			bxfxd5five8
			4fzlpr4nzmfive37fivefive
			vjptnknvlxhzvfpqxfive5four8
			9five1dr6eight5hpkx8
			eight7fourfourxlrztj64sixone
			twofourqqprdrkmrbgtqj5oneightb
			83three
			threethreefourtnvddnmsixnjhrfmhmxz62one
			8fivesevennine2skseven2nr
			fourseveneight74hmslvqssdfdsltvcsd
			38cxc
			1njgbbprzf5fivethreeninezgllfmsxfq8pgntvq
			mshrhzmgbfourthree8
			3oneqgqfgreightfourhsxlcb
			7sixfivekronefbtrjszbfr
			hgsqk4xfjzkkxdz
			twoeightfq5rhdjcbg9
			drkclzltwovtblgppbtpzrcnlhhtwofivevcnlvxhbn8
			pksrcnqps5hzdvnbgkmgfoureight9fx
			87ppqndvcmtzrttwothree5nine
			fourfour1fivetwofive2v
			fivermshbd75
			47mljfm9qjnbzjmq
			1cqnrmpmknpzgxp8four8
			eightzgtjn1
			three2nfdnfivefourseven
			zjbbj5mxqnnsxml5
			8847rtqjrctqczeight5hqmrbzkd3
			onev5seventkpvrtq
			sevensevencfjbscdbvqlc12eightwok
			2dpnxxlqthree3fourseven
			3xfrnxtds9seven
			eight7four
			sixzkjrjf1s49xhk
			foureight1bsxmfdgpgthree
			crzjxgfldz9nine7
			dlrzoneeight3blfxhd6hxklgmzcb
			six1cdlfcsshkh4eightgndfivefour4
			threethree2xcsixqfsgxjhgf7
			cnjkkfcnninezbvrthjrhg2two2qzbrchvxqsfqhk5
			ninefiveqmgnhrdndclldxtjmqmkseven1lcjlqddmbnn
			zjqlxpn437fivemftgzsz8tsnnbgmm
			xllzq6l6nineone1
			vqkjtjdnine4onefive97h
			two1ltbdnine
			ninefive62
			eight8ninetbmtxtmmnfllnj5
			four9three3ninefxttjkhtkgvpvcbd5
			43six3twoeight
			fourfnctllc1twosixsix67hlgt
			fourfive8gkblmrninesixgfkpqkleight
			5ninermhkttx18three6five
			51one2jvbxs6
			6pshzkvn87jz12three
			62nineseven
			bchls4fivelpdldjzmbtwofour28seven
			274four
			cjnjksf4cdpvbjfnine2rone
			krxeight7mzdbbknqdxpzg4eight
			1one3gx3eight2
			5nine19eighthvcmzbltkfive88
			11one2sixxgvmg
			p51rzprxgldxcznjjonefdjgfqbndnjn
			9jfpvqhpht6
			9threeseven5
			seven62
			threeonefivetwo91three6
			three3ksl
			xhltjp6qt
			9qtxtnlhgg8four5nine3cvptllv
			267jlqgljqfltwo884oneightrb
			141eightnlp
			rxpxrbvgrcmhzone3one6ppnzmg2
			five5sixrpzjqgbtgdjlmmprh1
			onefivefivekglldg5six
			threeseventhree2
			one1fgcxgjxrm4seven
			mstfpfhf7seven3ninezvrxeighttwo
			oneoneqpgdghxl7three3
			twodlbrctkhjtwothreefivetwo9
			fivenine19seven8two4
			vpjkmfsfrjhhbksevenfivervdm514
			fourjqtggglnfive32kzcx
			lcrtvrfkzthree4eighttwo9
			eightnrvtxpqxjztttqvgmlqhxqj1
			2ninepqntclhbk5three
			thfdxrnbbqc6
			seven8mjpmvbqxhfhxgjdlltnine2
			hqbthreezqbhlnthreenlfour8kgzzxjcsgz
			6jksppsskp63threenshc
			two8nine
			bsixmstxhhfnm3bcckpjp
			4fourtwo86tkdkxtwo
			xc4eightsevenbdseight56
			fourrnntnp9ck
			onesixflbfss8two2lxhhjdhxntpjpkds
			threeone71fourcpcsxld
			bczssjbdzbonemtbrz7five8ccnnj
			42onedkxtrhhm1nkn
			nf6ssm3
			eighthltsggc2six383
			srkppleightmxzmlk38
			336tdfthnj2fghhklkg
			zhpsbbjzzk3mxzzsnvdbs
			1nine6fiveninerdng37mfks
			4ninefour2kznine3
			fhsjfivehs1
			one4qzbgrzlcfjbstfc
			twohkrbh8zlhkgvfivetwormjq
			ldfzzjzkxx9
			7f95stwo3
			xcppkmb5ntnrzrqndh1oneightxm
			threebhvkdbbt26qdbcpgm3four
			mvxd86sevenfjndplrd
			585
			eightseven51xpxxzqnstzlp1
			one8eight57lvlbzgclktsix1four
			255fourone72
			onexqrbpcmc1two7done6
			fournineqbxgklbpqqhs2six
			dnptsevendbphglkqtwoxgsjckf4
			25pskrxeightfourjrtgxonetwofnkj
			sevenfivesevenqtgqlpjkntdnkxqvf4
			1xklsljm8knrm3five5eight
			sevenfiveseven9bnprxvjl
			threevzmqxdmgc3
			fkzvone237lgqtxfcnvddqrdmj
			5sixnsix6lqmsqdvvdj
			287fdvgbtcq
			sixsevenninelpzlclr4
			fivesix7
			73drvqt7nsixbzt8one
			xksbgk6knc58oneninetwo
			lknvtktz62pccjdnc6
			7zxskgs
			nzdtwoneoneqvmt9pmvnthree8lksxhxv
			3hzdrjckdsixthree2
			hbmbcrgmpkxzjthree8sixz
			94979ntmkxbzlcone
			bsb3threesix
			jpmtgfcgjpkbx8
			3tqnctzbmfivebninetwo
			9vrpgcbmdktdprzs
			fourfivefourone9fourqnsjlbgkv9nine
			5vlsbplrtonezqhhzt5bgxkspsf
			one6dkckh6four2gqztm81
			dtoneighth871
			five3mzqgxnbmdbcmnteightsixtc
			4three19qfourtzh5n
			8threefourppvfbrfp4
			19five6nvtgsp8
			sixtwo9tqpqg1fourtwo
			1tkzn
			twofoursevenjp2zphqlzqmmbskkmxmj
			one1vgvsgbhtwojmgr
			nine2phxpfnptp
			rqqxqslzqjlnfb1four
			17gkhhffc3oneeight597
			jjhclx3
			2513
			3five91tnbkmxeightxonef
			gpqnkzt2sevennflfrxdonevgkhjrgeight
			1one5eightfour5hckvkpxsleight
			41rbglbkmqr
			one8eight
			9threevdbtbrbrgrtcdv1
			58ninetwonine8three7
			nineznvtft63t
			2nqhjtvds3ksfjkqxhvseven7
			41t279zsgmzmjk12
			eightthreethree12ninehrsbvftksstwo1
			fmgcfnxbs6vrmtxxvfdz27three
			17qkrps1
			three4two4rnnslsvxmsbcpvnbpfseveneightwokcn
			58ninehxcsnzfxbf6xvgcrfznrldqntsbsjmr5
			355knfjsdqjm8
			htsrn3qdbskfsd211
			969five
			tdbjsvfxv67htbpmfx
			6l
			pdzseightjvjxlhgjhrnz9zzjbcrktjc99
			fourzqlhcjksixthreejrl9
			""";

	public static final String alt2input =
		"""
			3fiveone
			eightnineseventwo1seven
			9h1xcrcggtwo38
			nine4pvtl
			seven7rsbqpgxtjzsgxssix
			twofivethreepqgsvrszczrthree7
			44qcrkvr1two
			zstrmphtxdvdpsnhpnq4threenbjznsb
			bhgxhb41eight
			qhstsbxsspsrfourmtvtnfhxlj699one
			onekvhgkeighteight6two7ninelnfzbr
			xsixz5six3gfqrzmpnjgskd6
			qfrpksmzzvfkddtfh6838
			mztttgnxdqt4
			8threesevenfourgbgteight5twonenjr
			bpzkn2rbbjtdtlznl
			glckqhjsbsznseight5dtnxnsix7
			2shd3ksrtmbs62vvdvhd
			9ninemdkkqjzjfour9mzspzjgmlhfq
			7twoqjbshcfxldnkc33one83
			zstxvfdthreeseven7mdfpgzgfourdfshplvqflfprt1
			9mndn31msfprm1kpk
			tmczplnmrsevenhmhprtllcktpr8eight9
			49nine29917five
			6qspssvm8
			7fourninefourcpfgpmxqjsjxmjfntwonine
			3nxfjmzhseven22one
			tzgnljxhs9nine1lvqgsix9four
			eightthree9eightfourninexl6gsdhljppfb
			9g
			2xlcvqrxs2eightznzdghnlvcfour8xbzk
			xgmfqvdbsn7sixnineseven5
			65zsghsnfbseven9
			7skmb5
			dbvjtf294threefournine
			21hbtcfzbjhsbxlhd
			27four
			jlrthree9four8fourhqnsevenxqlmtsmzt
			gjppzpvglfsvdmonercrsn4
			3zzxmhc
			ldfgpzjmtcbj3jvsltltjv1eightzrdczhrzpcssrsrxbj
			szblqqfgxhxkk3fourvqnpzf1onesixthree
			vsb37three
			8kxdcgmpb2sevenjdvc3eight7
			kgrsmfghvfivemhxnfiveqzzspmgmsvvghzd1fzcrkzdfsb
			5mphlhx5dmcxxcpcxsrdzdninethree
			hmqdkgvk4twoeight
			2rjxxdcgtq5fivehzslfc
			srqzfsvpfbnsvninetwothree6sixppsmfrtcrxxth
			4fourtwocdxnzkbznnrf
			4six419qpqfvfdpcrqvsjhgsfgrkpfmphseven
			hxdcttl72seven
			qkoneighttwoonesixeightfive2tzmrtpcthreefour
			bnjqlftwobvsvjqptdp1two94twonej
			eightninetwo278prrbvmcmf
			seven79two
			one9bx
			cfpbdmjbcd27sixfour
			16snbjgjzqxzplxkkclpxzdx
			3scbbonenine5fivethreenine
			21sixsix68oneninefour
			6ninejmtrp4fivekxgdgj
			6mhlddxbshqbseventhree3two6six
			7four8smntchbmj71oneeight6
			six25four196one2
			2foursixftdbhbtd6
			fourfonekfsxdgvglvtrnrrjzmmkzxljm3
			3xckjzm
			six9ssvkh1hdxcxmsptlxgdd8eight
			2eightfourone2ninezslhqhdlcp2qxv
			7oneclztx7xsxhrhhggfbhzdfgkdfvsqjskmdzj
			fouronekkxqtrkptqz8
			klccbbvbjsix3fivenine
			rjrxdxdz33nine
			sevenninen5
			nineseveneightlcfrlftwoxlsmrjxnkk7zlzpbzm
			rblvkfltqtbm18one7bvkzvvqrlbtf
			gdcbszzf6sqldx
			twoninethree23sixninebnzzjgqrlfktt
			62ninetwo
			fourfour44z8
			6qxdvmpkq
			sixfivesixthree3x
			pcqfxpvb1threefive77
			pncgzkppqqhmzmzjmzsevenxbsggc8
			fivexxdvpl32rdsix2seven
			9blqpthpvfourfour69bprn
			8vxsdfbdjmldkvtkbr4three
			threefive8
			ck4p6
			two9bpeightldmrnzbt
			4dpd
			one7four6rcvtvfmzmnineq3
			4njtvkkstgmbjptcpdpzdfive
			2tsl1sixgfbbpdhxgrfpt
			947four5four3fivenine
			fivelhtkgjhhzxfp3
			7one1three4sixmcrjlkzrj
			9fourxtzqsjjmxfivehttj15
			2lqnfrgvdninedrdj
			9rtxjbffmsbsqdrnjjdkb
			twofour8
			1sixfourone
			nine1xzpqkfhmzkbqtzh
			bbh9fqrbt94onebdppqmtjlq
			one8nnngz5
			vchszvlzpljt1pdv6tqsk6four
			sevensix9qmjkrglh
			5threenine7fkrtbcsevenjlxrkltp1
			ggrsfivetwothree687two
			jbtdsixthreexxvjbft5
			1four2eightseven8one3eightwogrr
			six6vtltzh65
			7bbxlhgdbrh9sph44sbboneoneightxcn
			lptqrf9twofzbmbbkkmt
			1zhxmsevenlnsxmdcpz5one
			63one
			one3ninepcnphxdzvhvmcv846
			nkn6eight21one
			s1cnkm
			sixone3
			sixbvvmreightonethreesixthree3five
			bvbeight5sevensixchfrkjz
			hkfkczqffjmndzseven7fiverklvhv9
			rsfccvtl9seven
			fourczfive5threefive5qj3
			9fivexskp3
			tsrdgzcvftbvllhvcvzzthreetzzspvvjkrfgn9
			bv8twotwo9nh
			lbksl3cpgzlxjgnrpqslbsknglctwothree
			nine9eightqhcdzfcp2
			vckdtskc79threemblqcs3sixndlxfpq8
			1ggkrvbpsl9ssix6one8zh
			679one9nzsktvfseighteightwotjm
			threefive7gfzptnxbvvlzlxbteightglseightworsq
			843trvvsxdkfspsixonethreeone
			hsrqmrfvvzkczhphc8147xrrnzldnvr
			m6six
			oneccnxglxone29
			37jvhjvvlbv223mmnrthreesl
			bpeight1
			twocd8
			4sevensix8twotwohhmzr2
			djpbjhrcfour5vbpkmsgnjckrkvt7
			sixnfrlbv8sixrqgmt4qmftxnrmx5
			sevenzvhhfourchckzrljhfivevjbxxh91six
			eightckclzxbkqmkncvfdxfx84zeight1
			9stftdhkbs4
			qrpbdqzsjfj3seven21zktlblk
			seven87
			lpms5
			pdgpscn74s4onelh8
			7ljbdfour1tnfive81
			3rjlmtdvbr
			lnvjkkgjc5
			7vxlqgxk5lkfdnsdh3
			jlpgttbf35fourthreenine3cdfxbsdgslczvpjssm
			eighttwoplpbcbkltwobvzccbhxndndmgxdf5
			eightoneeight4
			rkfx585
			9fourfour
			7pxcnjslqgp98sixpkhvqjhjqgeightone
			fiveeight1fivehvqrnzxqlkrcmd
			sevenvgzkmhst8ninegcgzxkxr4dpdjsmone8
			fourgjfncfeightlptffqjhrltngg6
			sevenqkjdtxptzbtwo8seven8
			757ltrfkjzeight57
			1twofoursix2xcqkf
			7ninetjngrkq7npldprkd
			kqcgtnxvjv9
			nsvqdsqzthreeqtzzhpd6xcggbnkxfone5
			eightzkmbhtmpxxjlfqqvmvmbvgmbtpcbpz1
			six1tpvs2sixnctjmdlc
			695one92sevenggrsc
			stpr38onedftngldtx8lrsgfljrc
			1vbzxfive4fivetwotwo7
			kdsjx2
			dntkrpshcmqpgskcgsgvq9
			6pskhmkpfive1nmkcvonemdfpqdtvdl
			fvfndcnine7khthreehljzshdbkblgm
			eight49rcbnkmdthreegqlgvksvxksqf7
			22xsix
			twosevenfive72bccn8rbzkfczgssqcg
			two9hclkszjmxonetlgjfive1
			dgpm6nhzkkqng
			qrnkpxnn3lltxqxxjzxdkxhlkceight3eightthree
			two5two4one61
			59ninesix
			3nineninesevenfour
			9cvsx1jzrxhrxshldtbbn9
			65four
			three738
			cvj2sevenxrsdqhp
			p255hztrqj92sevenjlpzm
			qjsdgdjrxdsjdfx7one
			6fivexm1qhxbgcvkvxb
			fourxdnpqmjs3bqnzzphp1
			7nmrndvq7jnxnlsseven9twonelxb
			four1sjnh5zkrrlxxj
			hphshrj3cztfgm23two
			1zgvfourninefivetwocllkr
			1mgqmktstwo
			5ndrsix5tdmfcjbgvff
			4onefive9918eight
			sevendbtcttvmcnljp3threethree1vmsggrpx
			four5llnsvvcrcgd7sevenldffd
			nine2five9fivemfour
			2cpbhssgzfsrhjtq2onefmpdqfivehxvbzpfmg
			spglsevenrtbrkpnrq6
			bbfqkt5nkfrzl99gxdlzzsb
			6csshxkzkshsxnnineeighttwoclslvdkjkc
			five9pcb2nine4two4b
			brzrd5threendzpvs7ldkjxmpqqr
			one4vdtwo
			fourseven5493dvldshvz
			1gkmnj
			ninethree8
			vshbcvtvvf4eightonesix
			7nine485eightrmxbrd
			dctwofour3
			18ftwo
			twotwo8rzdbgeightthree
			sevenztlzzn38nine3jtnqjsnine6
			14qrvcspxmr4
			783sixxkkhrpqjrt5ninesjflktt1
			73five3
			nrtwonetlmkldqrcjqrdn6gptzdclninethreenine
			8sixxqfl
			sndlpvjr3
			hx5zzlqk1571three
			zvl1
			1twotnqcmfqrnr33rrhghsdqddpmbzd
			nine1threevcninetwosix7m
			six2onesix1xqjzczdrl3
			15jkhgkfzseven26
			fntvfkhfzsfour7onesevenfour
			sixone653
			hnvftxjthnmfive1sevendfnpkpffgj
			rdktwone9fourkklk9rsseven
			2fivefive4eight
			vmfour34lpjzbr517nqkthkljv
			hk9rqtwozr189
			fivefive3
			5one6four9twohsnjkcp3
			one77twoeighteightfive6twonek
			vrxbxdgmtwo8tmglzjx
			lp4ckhf
			srh2
			hsbkzggsfgeight5qhblzgsppxbdlpvhvcpgkndzkjtmpggpdx
			sixzvhnnzffnsevenfourpkxnvc7one
			fourvgv19g6xhphkdt
			fgvl8nine42
			four97five4lfcmzchtbmtvtvbr
			3onesevenqtwo21jjpgtwo
			four44fournine1
			twozhhvcxck6
			skpvglmddmxlsrt3961nine
			8twoonetwofourtwokxrplnrvhmthree
			7ktxhsjdml6twofive
			zfdtjbrfive669bscgkpeightseven
			zmghddqkseight5two63three45
			x4one
			5one1pcv9kkninenine7
			b678two
			x7
			97foursevenbhrxdpkv1
			rjkfdbteight8fivejrspls231
			six2skbfzvnlbvfour61seven8
			2mcqpccjfs5
			8tm
			kr9pmdxkzjsg69fnkrrphlxqpsqjhzbznine
			eightcqmdq8twozbbzfkxlhsmmv7
			xvgflfourkhn3ninebx9fivedzsmsnf
			crrsnkfmvtwosmjk7
			8four8796
			nxqhdsczcgnvq5
			8five5two9three4
			6clffour2eight3zgzjnnmfsix
			1drp4six2rtszhttwotwo
			zkmlfive7
			245eightnine9142
			sixfive1
			xvnbjvfivezhzfpvnsthree5bvvfive5cxjfkszprp
			3bbvmq
			13
			946five
			5twooneeightbhxfhpvjmlgtkccqgmqjnq
			mlq7
			122fivetv4
			fiveseven833pszfqhbt
			229oneninenine414
			knmvqkkh1cjbbjnjzrtpxdjznn9six
			78nslms
			vqrdsmtjtgfourninethreefivextgtwo5t
			slnrndksnb95three8vrskzqzfthree6
			4twofhhqdghjssjkkcjlbjthree
			2xsnjsfngdqpzfmltkrsk1hvhktwo52
			sevenxxmxmmngqmdx2lbthree
			five823nine
			dszvsjnzn7
			tmvlsfive5prd
			six3nine
			onerzskmfthree3sctlkhcqrdzc97
			eight34kfour2cdgnnkdff
			dmone3three5hjndcbbonethree
			63five5513pdgczone
			6fivechs4vk
			3zlqsxzqdnpseight5
			five6eight13eight
			zjknbtptmdzfour3one2seventhree
			sxshgxbcxs64dmtzplkqnfffkpz
			rml4b65htpzcrlrbn39
			8tlpnvnrhjb57
			fivetwo1five
			9nrrms247qcffourone
			n6two2sevenvtfsxhsn
			dxjtpsfjcssix2ninefour
			qfldkljtbqc4five72fourjqbkbrh
			3nine1
			jflrjzjzfour3four8threefouroneeight
			fivefivesevenseveneight771lhpzhb
			nrszb3eight1tbzmmps79
			8kkskdtwoeight78eightvbmv
			4bccrqxmrvd1three
			nine93fourjhspbgnthree364
			11q
			three7fourthreeftbxtmmm
			mznine6six1
			sevendzpcbqjfdk83twobgqfourmkzfzflnn1
			twocvbtssm72
			keightwo12
			fourzxcbncddhthreeqsccqgsf4crzszqdd3nvvjsix
			jmh3ggvdp
			12fiveninefoureight
			3tvlmfpkgrdthree2phmllhczeightj9qq
			sevendndrnfpfzmgvfqnkp8pcjlttzfour7
			dvtbsjreight1fkdlffive55bxzpsrnxtbfour
			7threeseven
			qrhzdlsb4five
			bvdvjfqvtrtqntrrnqfpf87njtjgxzkgbcnine
			z927
			one2eight
			7dpszhz3pfnrrtrkxjn
			8mfkvn
			258lkpqdc3five733
			1nine1threefour
			nnbfzxdmm828cdgvfive
			threetwothreethreetjzskgfive4
			six893sevennine82
			3ss48phseventwo24
			xgbpshxnkvcppnninepjcztcsevenqbnjcjftpxxkpqp66
			8mlkbpdpftwonine4
			5three6six1seven
			91onelrttnjrcqjtnrfivec
			322one
			sevenmfpxvntvkpqvpbnnbpr5seven18sixeighteightwok
			jnthkgsrone6vnkdvkjznjnboneoneseven7
			five81472
			2onefive
			nine9oneqfb7
			tcf2two2145eightsix
			vdjhlrksdhcone17three9qoneightr
			fiveone82228bgrr
			5rfxlfbbjqninethreefour
			eight641
			2pjmlgrrzvv
			kpqsxmvhp4twohnlsone3eighttwones
			35sixd9eighthm89
			8four5onethreeqmdmttvchslfvnqrbftthree
			fivemmbfjmq1jlvzsix1hgkbr7bxcsc
			eightgmjxseven5fivefiveslbfsqrjrnbhqzgr
			xr18oneqjgsnjfzcsix4
			9threefivekclcmrnsix654
			onelnh6sqvzxeight9
			6vjjpmmxxknineone79
			cdsfmz97twoninetqhhtsljsixseven
			8five6
			ninepkp3
			eightfour4fqtrlnzt
			one4pttsvonexsj4
			fczlpseven261
			9six6nine5nb4fouroneightv
			2snzvzxkbbpcvd
			mvnqjkcmkhrvnsxt3hjkj2ninethreezzbbrsdone
			zktwonemhqnxssxftwotsd1nhfmrxpffoureight7
			qfhlmpxhxpthreennlk7chk7zzmlqxmtlk6
			7dxhzpmtwog9
			kfkmpmzxhn6four87rcthd
			bvplp656vtxxlqvmm6187
			811beight
			39586547
			18twok
			pfxsfxsvkjrb9
			38z9trcxdbfivedmhtdrfive
			19bhddbmbkbg77
			four522
			7vshvtblzonefbfcfgsfive2
			mgtwoneonecthreefoureight37eightjqlxf
			eightnine67gthszx9tzxczcpone1
			fourfourthree2fivejrfgkb6seventwo
			4dnreightrv6ql3
			csfgqxjdvm22jjnr9
			42szlhdvbdstllzldtcblgtfive7gnctbrmvmn6
			ztwoneeightfourzzsck7seventwo
			two78
			1hxqtdxjqflthreesrzzdbxmfnvk89three
			rnprnnpbjq7fivetwoneqsh
			hkpjjpbl3nineone6pcszznjft8d
			gcbtzdtkhnbbjnftwo2four7nineseven
			3foureightonesixrfqrjlp
			qvftcskmxdvnsrzqfourfivethreenine99slncxvjrcn
			six5sshpxtr88
			7twofour
			four143
			vrxxmzfp8
			four9tg8bfonesix59
			three3onezsqdtkrceighthnstg6three
			7seventwonine
			fivetwofour9nine1two
			twozfdvkjzbtwo6xrjgmfgsxv
			1dqfcfjcbxxgxrksixnine4
			rfpgseven5ninezdmbx5
			622
			nine19fivetvm
			eightthreelpj58qjlnhr
			9fourjtczvxfourfivebmzds415
			3fivejbgzdsx
			fcqdbxgjf86twofour
			nine6oneone
			onefour1
			onestc6eight3oneseventhreeone
			seven2six
			plbgd5nmppgfpbtphsxldrllpmnprm
			1three14eightbvnzx83
			four95kkpjsttjf8one
			mrkrgj5xtqvvzpmxn8nine
			nineskg78nbrnonelsxfxkxlrc
			qxnvkcx1one
			9ztbs2grvsixsqt94
			sevenjhtd7
			qjb78nine29
			3oneonegjtcppfrjs633
			3clhz
			1v398nine
			mqlsevenlcnblh94
			5fiveseven
			73rbhnnsixsix7ntssps9v
			svjsgvdsrspmsxzkczseven11nine4
			onefjncqnsbsvqqm4478
			mfzfzjhc1zgbtt
			six1sevenseventwokvbtwogvpstm
			one56nine
			8sxhbpfrxfsixl9lthreehr9
			44nine4threethreedbbp
			seventhreedp66gnxvfnpzvdpqflnx2
			twotwofour37cmfzvxqjp5seven
			1twonexlr
			sixtwosix6seven7g
			63zscqhtonebtcjfdjqc
			fiveklbblk4eighttwonefdf
			seven7one
			zz361tmxqdpmgseven6
			5onethree6cgkfkdcmnine2blhxzqxjqk5
			threefour43dp
			hcmjsszeightthree4tsnppskn78ggl
			7gzqsthtmvszmjvcgseven
			onethree6sevenonetcxsseven
			3twobzbxc9onelxfkvgsnhteight
			hnljcxrhxhjkhmhtffjrcqmeight7kcjmhjlvmgq4
			5nineseven6lkxzlbf
			49jxmvnql8crs
			qgq6eighttwo5one
			1xclqfour8bgqsjknine
			mrheightwogfglthreeeight6threeeighttwodfkjgp
			26three6nfrxkhqlq93seven
			3two4gjzmvvnrhdthreekrqhbfgssjghksix
			sixone6sixfour7four
			zbsvkkmhmcone677hmjsevenrqmng
			mqzjpd5foursevengxmsbjhl
			lmrpmthreelthree19tvbnbfqggnftwo
			x3
			6zrhpdnxqpbfourltbvhlglvseven
			3onesixeightsevenqjjclpcndtzgnzcv9
			fiveeightrm6
			cfqonesevenszbvlkdpfourninetwo6five
			9lhlsbntzfourhvxfxgfjfivezcvqfshmldcmmhb
			oneseven28pjmqkd
			one5three284fhrbztwoseven
			jmhj2rnf983bbzsmts2xf
			one981eightr4
			tmtwo2zrjdd9five
			4eightsixsix
			q3rszpbkftqv
			6zndd7
			7sixflqjpcgrh4281
			89ninehbfklckdglmcgvm2
			712gsfgtdvthree
			nine5knlzninerspkdklnthree
			dhjmgthfiveeight79threefive
			87bn
			4eightkbppvkx9sevenzqcfrqlbxmk45
			fourthreekvtvdrlgjrk2four7c
			six6dlmmmvfkseventwoonesix
			47rsjqzcqsnffourqdggnkpgsqjgprhrx2
			ptbtpthmkeightxtzjftbff6dqzdq7
			48sixcfngcjngjs3bszknmgzjthree
			nmcdlgrrdrmrrbpfn1
			5q6crrhphbmqr8zdddmnseven8
			fxlkdnq6
			threeffvsrjdbtfk6trsgmkn
			one3fourtwofcqsgcvvg
			eight8onexvdtthree1pzfrllrjrtktzvnrp
			hlnine3
			54three3zxbdtjrlzone
			5qjnpjvnzpfive2two71rphp
			njseven6four
			bgpkmfcbl72
			9vmjgvhvfvd1
			ttbmt46two
			mksvjgxsbdnlg8eighttwofourthreesfn
			mtjm6twoseven46
			fivefourcktdqsdlvpdq1eightwolc
			45twoneqs
			sevenplrfqrhfivejqzrnv3
			9nine4threetwolk6sevenk
			5qxpfourfqtg
			34cpbblldjfqpltcntpzninetwo
			7eightfivehczsxqhglmtpsxk8hkksbzr
			69two9
			6seven33pggfive1
			sevenhkhrj2
			4phnnpxthjn8
			4vnnfqdssrfive8seven8ninedfhl
			frhf15three4vvlgthree
			4nine3
			57hlrhqmxxxbl
			eightjhblpnjk786fivekrq
			rj9twofour
			lmszmtrhpthreezbdghgfour7sixtwofive
			ninesixrlxxsskgjpqfdpzbthree5
			qbddmnpgskf1tpfive34
			fxmninejzl319twoeight4
			two7ckzsmvqfcbfourthree25
			xzhqltqmdfourqshqmlxpninecbrsclzftwotwo7three
			one3zdppmxfroneighthb
			eightsix8tmh7fivesixgbdttd3
			pnhkxlcsh35
			four45
			9sevenfivehxr4eightfour8
			rmvmqbclzr5bmsxdzxgptlhczgsh42eight
			bpbbvbjrptfourqpkdfqkjcrrpone1b3
			2six6
			ninesixthreexshfvpb5
			3xhljmkxlr1clcqkmbdrmtxptgl
			gfkhdhgv27ktc7foursevenseven2
			eight1eight4
			nine4vzdqjs8three9
			2lhmbfzonetwo9
			nlhkm83cslc5three9sevennine
			thhllmnnpxsbtjvnrnhq8rbvhzfrxzqqqhccqlzfggseven
			four6six8kqmjzk8
			gcrqzmbsh7seven6
			8five575four9six
			four615
			41xzlprtjncrlzbcgvbmclsqrnbdone6
			sdphx53c
			threefblfr1seven3
			xqh1one
			qztslzlkheightsixkrpfourtwonine7one
			nhqdsngrf8seven7dkbkfbdgdcjvnmdbzx9
			7qrmrsnhvfive4klcrkkbtwo
			qpltxmjl3twosixrnvmlqvgrgmgninetwo
			43lbsbgjkng1one
			lzjqmlxnk452zrglhpbpvtwo
			fourlmcprk36mthree
			cssthvvxrgpks48glbxk
			qpmkfxk4fourbmnbfzhgn2three
			zxkntbdnm3fivethreesixmkgztvrfpkjgxljbm5tt
			1vlhrcllfjtsgmqcvhcbcr98
			nine6dlkvtfjfnq3hbxxm
			eight42
			mnrdpvdpklgkjnrz4
			1seven93ninesevenjqmeighteightwoz
			seven8933five4seven
			9lldhvdqdzvdgptsmf1eight
			7fiveninezfourkrltflg
			threeseven9
			7hjfzpltbjqbkx1two
			1twoqghxlrpmfourfivefonermntbg
			77eightjpgmmjst4
			9three8586nine6kb
			three8ninetwothree2
			13xrhdzqsonesix43bph
			foneight7
			29one
			rth7cczktksv2
			frrpbtjjcdfccdl1three
			one5six4
			ninehszc5svnhfrqm
			threezfrmbgmjzg6
			9eight8one8fxlkdjhql
			fivesmtkcsskrq7hxqbfkbqlninegnqddjrvxb
			zfivehhknpdm7fngjpkbvone
			7five8
			qkcxcpjzggzdxrfhlbsdbq17
			654mk
			2mqtgbmsnhq4zv48jzdchccdpzhs
			rpkfj1hkrztwosix4bktdfk
			seven9bxjmvrbb
			9threethreeeightppdkjzltclnq8sixnine
			7seven92
			567onefour8bsgjtrvsxkjlsc
			1dnbsjbdsrsscq3ninefour
			vbpkpgssljgtxdfivethree6
			eightsevenrkkjszmxvxtwo9jpvzldd6
			one7523vgpvlkd
			foureightonepeight4
			9fiveeightone
			nine7one9
			g328dbspnkseven
			threeclqhr97five
			8onefourffhrmfkvctt
			2pzftpmvzfive
			433tvdzmcrdl
			five42ckvlkgkjxh35sixd
			nine6hs
			99cmtdzjtpxk15c2
			tconexjkkh9
			sevensix5oneeight
			twotwo4ncmpzpvvdrsxkpnpfkjseven
			nine42
			7sevenxntxxdnfckbkdh7seven6eight
			2foursevenzvdvhmzscd8gmlxxkqxd
			5sevenrzntpronehfpbdcmffdscfvsqjcvnbtqzpph
			threefoursix6ninegdpmtlsix
			lxcflpcvgctxhm1nine2
			seven4one9mkkznineck8ptpc
			seven4qtgqrcvfcfourzfdnx
			md13xsdltxltqhninemjs
			fourtxtscncgxvp3tqthreeseven
			8zzvkkmzhr7sevenfive776
			91sgceightvgzjdkkkthree
			mfmvgtck5gbjstzvmfvtmr
			nine57one84sixmqt
			threekslcvdzlhhq6dqtkp9two4
			2slmvrvz38
			foursix6qlqvzqbdzf2
			mftwone3eighthhcsgfvrrj
			174bx2ninetwo8
			ninetwo7mzlcjkmj
			37four2
			cjmlmtwovrvsbmeightthreethree3lkq9
			cscvfbgpjmonep8hmlnvrhvgsqrvcp
			tmqkssbt79ninerfgh88
			qdsxzxcseight7
			eighteightnine8threecbcnfdtm41
			ljpcfour1368nine
			hftwoneninesixxxmdtcfd8lbvqdjg
			kjktdqqbfourdvkjlprhkzgfivetcddgds1
			qjeightwohvvdbqdnbknktv8six4four53
			6482cbb1
			sixcczlxcthree35lqn51
			rmnmjsthreehfxsjqlpkjxmdkg7three
			94lhpqldseven
			fctfxjvnine7
			sqnthxzkctfk98
			8xpknqzfkone
			9threeonetwo
			59d8twoshphfzlk
			26vtseven6bsfkgxmjqnine
			6nslcxpglfoursevenoneseven
			sfvpkkvdkrfour31one8bqcrtwokhqp
			29vrcx5four9
			43two
			eightsixpcmhlk7nhpxhmnrmponesevenpkfgxmrfnq
			svfjcqdtnmcrtjdgseveneightninetwocnbrrbcgmreight9
			25cxhtcxvgkjlbcshxrfour7rcnkzmm
			onethree14gvjpp
			sevennxlncmqpkvlhbts1mhpfxzqf8
			six6fivesix
			3fiveone8one6six57
			tqgdrncxgpxpxz33
			vrdxxljfeightseven63b
			onetwo56nineone9kkb
			nvpqcnrgqrrnzqsqrh4four
			67twobvxksevenztnhfpzkj9
			rxddljfhxhlbqqrllk3six
			8twosevenone
			onejxjpcnzljjdkbkmgvvrjrkgxgpqzdmpjzt4
			ftbssc2fgtmsrjbr
			djxnine1seven6sixone
			grqxsevengkkgv83fhspzflvfbqjrm
			ctsj5svksdtwostmft8twonine
			two9thpzhrcvdl4
			one2seven2plxkgkldxcpqconecfnppseightwovz
			prleightwoggdqszvonefrqhh791vxxcfv
			nine4seven6ninepbfoursix2
			fourthree8threett488
			six984three9r3xjnmvp
			261
			twoonedrbbmvrm8fivejsix
			6onethreethreeeightxpcchknine
			two55oneone3three7five
			three3threekgpsix
			rqvfvm9ninesixninesix7pfsxcrx
			4oneeightsixfive
			2fourthreeqjppmfjfxnzfdhlr
			9gctq3
			vtzcng2jhrhgsqhq
			eightmmxz6ninenleight
			sbzllxonemjfffkhltgpshkmlrjb7oneone
			7fourfivefivefive3qjfdzclghxtc
			fourfour9hmmlhhbxfour46twomzsgpkht
			fiveqc45
			2bvseven54sixghpnhleights
			2qlhvfive6ffpbhftfp6
			4sixone1sevengqqqjbzr
			spq17sevenhjfkkjzdf
			eightphqcjzdfzpttgxbsix1fvmnvqczr
			9hxzczdhdl8oneqkqdlseveneighteight7
			gllbrsevenfour4vfcgth
			lxdqx59mvzfjcsjl9
			three2eight3seven8rzsthree3
			two8seven64
			eight4dqqgeightseven
			71threejdzzk
			6fourgtcqnjkzjljksdqtbddpvxznvmprjtr6
			3fxkdgm
			eighttwo3four6zg
			6rxlnjpgkkstkbzj
			74pcpzgndmtjgngonejfskscqfgm
			dfssmbbxf873rhrbxnfzcp
			bpqlnrtn5eightsixdschkk
			lcrhcxvbrqhbz1one8
			46mrpfrtpnzdkshjgfxnrjbtntdnfive
			tlgtzp86twofive
			eightpmbdvzmdmpfivebphsv2pzxtcsrvtgnqnhvsbdf9twonehc
			xqkbgbseven5
			bheightwotwojl1one8
			five7zsixgsmtvpxkkdrjtqtfjdjln
			poneightbrndfh97kqtpgcstvnine6
			svhgqmjgfoureight7twodsmcnjh6mmncjvltp
			79sixfourdlprglcm
			five31
			ncnmdbvvhnpqxzkktjzbsqxb42
			twoone8mfxc
			sixtwogxhhvcqpvzjmnltcdskdthree3nvdqeight
			stwone15
			threethreeghzvvdkd7
			fivesevenr3nj
			five6rmrccmczninelshone62
			8threet4nsrrkhg6bprcjtrpgclp
			3twoseven5
			26twopqtvsks5
			ninemhgqvchgzgndlone938five
			5twoprnvvvfcbninexxfrh2
			6fdpxffv4
			ninetwo5one6nqngsbqghbphngmone
			kvqfvnxnine9552
			1lmht
			6jvngqeightqnp925
			one53rqlbdzfive453xp
			32gntcntdtcv
			6qxdnhpvrcd5fivenpmqb
			sevenninesevenfive9
			98svjcb1nine
			777ctrsnjzlfbxdzbvckr
			6three4onetwofour2five
			27hdhhbv68sevennineclpdtb
			mknzmjqsp5xd7vdmfkbcfpgst2
			39twotwo
			d78jjxpgrgmpbthreefivezlbvgphnsd
			mcxgg3one7eightrzbdqzvfnvxn
			ncmfng86sevendqscgbmlrjnkvgqmzzfff1
			fivejlsdtbktwosix3
			npnxr6five947
			2prjccpmn3hfnxpqht8nine5four
			hfqrqpzfkqllthttmb4kcvfgtmp
			2fourfour
			6pj9fivenmhdlsx
			6csv7ninesevenlzgzninesixsthrlvsst
			7one83
			7mlrfqmjq47gfgpqgkgmpq72
			six5pnslzjhthfour67kcvgsix
			ninetwothree3
			vb91two4two
			eightdqmnsxlhhkz44two
			trzzone6tcvrsznine7kdctnine
			nineninefdfnxsixnrq2ninezrn
			bl79eight59
			jvjxkgjrbqdmnzk432sixmblqqmpn
			two39hthree7
			tdlcjpj5jhslsgfcx
			4two9jzdfzbbp
			9six7gtbk15vqzhhsbtxgmcx
			7vptsbpmq1
			59nsfbgxkvphnqvt
			dmffndtn9
			gzfnfsrdmrgtrbbsfive586xhrc
			cxvgfjjvbtlvkpsgsknine4jjgntjjzgfqrmlfbx4six
			3tszbt1six3
			ptjjhztq9eightseven
			zglcldrtwo5fqhvmfivesevenxvkxl9
			sevenonephscj3foursix2
			ninelgclbhv37
			fczvmgkzbm2jnzbgxhqmzoneqsrdj61
			1v8hpchzrvnzfbxninencjqdtqvgl
			seven6threeone
			five2sixrlfqftqzgks
			6three1xzgnkrzl2krjtxr
			zgkjvnkczstwolctzzlsevenone6bglzxscglsnjm
			3kvxbzmpvrp
			75vfz2
			vpnh25eight
			cnsdklvrsix2one
			kvlsjffgfltbkckcznmgrr8
			56foursix
			pmhgkfonehjdslqbdc4eight9
			twodmmsk57nx
			lfjvsz6fivekfivefivesdplsixpx
			twofivethreeqdgf3eightthree
			43sevenhnvsp
			threeeightzh3threeqnncknpxgseven
			4vbnmhgrmtsblrhrtoneljbbnvxmtvbfzssgone
			5kvqfxmlkgcmlmgbfiveeight
			55ztqqfzvmdppdpq1three3sixtwo
			26bskpdjql
			threehhgxmxdz1five94eight
			52fourzcbcfknlvlrnvhbnldq
			three49four8gshbnmxlc8vphklsvfmhnfss
			sevend95
			fbkmpcone555oneightkc
			5qddnptqdoneonezczvnsl
			78ttssqjfournddr986
			three4five
			jb6
			ht3hmrbxjsdvrsnlzvsqrj1rlcfggt5
			5bgxfoursevenrhtcqf2dpkvfmsmh2
			8rdsljbdggzseven4chgfppzmzkj
			hfcjpnrzsixfivefour6
			seveneight5hldmqltxonecbtknbeight6
			6ninetztvlzdmgj2xzbtk
			three988twodndrqvqpq
			4threejkrpgtlhgg6five
			4kgxgmprssixseven
			spfpone16
			xcpqvrthreemrggrvghqcgbqtkknvvk5
			2three84bxtwo
			gjmv82mgnqqgnzcgcd
			3nine4seven
			9twosnine
			nxfmfour8bgcgdkvb
			8three6one
			bxvxksbbdn3knpdc6stfbxffjggfglc
			sevenmfpxjgnpb743five6
			seven7sm
			8qxbbcxjvppeightwot
			fivetwotwo1seven8r
			96eightnrbeight84
			gljg4fiveone
			8nine6sevenmllmmchzjxb
			3twosixdcgl
			6xsfmfjjnz6vstfvhndhlklrsc73kljcseven
			threefour1
			tqtlxckrrch5jone9
			9qjsntszxb
			ninetwopqfnsrxrfstwod8one
			6eight85
			four63vgjflnctzssfstjx113
			1vhshftmrbseventhreetwoeight
			51bntvpdmxfznine5hbt
			fivebpcntvnklxxseven9
			2xq
			vjcbktqbxd55zhdxrhjqnr
			bxqndkhjg1sixvjct4
			2two1three
			kkconeight5eight9
			gz6two
			dmctnkrmone7fourdfqcfone3
			9oneightcb
			fiveqzjsvjqlsd99kpsixone
			8fivehfphnvtdf
			3six8jrrlnpj
			1six53hpmgsfqfourxmfmdqds
			eight7ljkrn3cntjv
			7rkscrcchttwoggxktqdptwodpkcsgpbseven
			eightthreeseven9threebdlskshg
			18xpklsg
			2sevenjlscgksv
			rmr3784sevenbgqfhklhl
			dbmtkvthree9mmqzfvmhpthreefivethreetwo
			566sixeightone6fiveone
			sixtwokf9
			lzgsrdmnl2xpps
			zlbmfmxtvhvng1eight
			1nine76ninegpc
			8onesevenxqjqrxflrb1
			2dhthree6sixthree
			4eight16
			2threenvllhnkqthreelhfnbp1gmkcgdf
			5threeeightthreeeight
			qjltlxkptr7threezplpxvqgrrn5
			ftkjg8onedxjcnmrsmf6foursctg5
			threenks5
			btseven2dlqjqpsnhxqmvqnjx
			43four
			64thknbt3three
			jgghlcsxl4gtwo9gfdcgxfour
			mvdkntknjf1stttccdntnrxhhdzgnrzznineseven
			2nine4nine
			4s6eight66616
			r4eightjfldjbqhcpxnhmsmzsjm
			3smktnsbtjm27cpkzvnjxone
			hvtccdslkb83xmlpktzbfournlklrqfxone
			seven5twosix9
			6dcqcfvcrbs8pxphlrrlvqlmjqfrlfoursixseven
			qntwofivezcpfknsvq51
			kdvszdf9tzkbhmthn
			79dcrnqfrnine
			dh8hrfvk2nine1fivefourseven
			rphmhjjnthree1threekbpbjhfk2threeggzjsz
			fhfive3vcflkznnpfive
			sp19onesixtwo5
			eight2ninejc4fivedgffn
			m5ffive
			436
			khpvrkl27twotwo
			7fnbzfdsqeight5fourone5one
			eight92nine48fivecnhzhg9
			83mkhqxtdt
			fivezvmqbczkgclsxfour3eightthreethree
			sixsixxlmh6
			sixfive98
			fourttlpxqponetwokn8tvkmrk66
			1chfcvrmxbtwo4
			sevensix1rlcnmbhs4
			eightftbfczpt8cgcnnck
			fourfivessnxfmlzzfiveseven24mfbfx
			49lqkxcxtjs2jdsbkmrvfninesix56
			fknjdjqcnm66hrktq
			1three24four6
			rpxtwone83
			5vnntgqnrpjh537ninebbkcs6
			three5mjmzhht57
			six4gfqcdbdhx96jvhktthree6
			sevendbssnxndrdxlbvssrt8dtrgcxxsixonehhstdr
			1sixfrzgtwo27pf
			6onevnnptcxhzgonethreetfxlsvxfmbqc
			gmqnpqsix7three3one5tpklvdfzkbqftkhrj
			rrslpzr1
			7ninedsvqtgntjdsqqmhgpjkqxkbpgmkxl
			sevenxhpjppgxqqz9nxgctwo
			7onefour
			one6dsntwo
			ghlgnsztmtsevenfour1bsctrtmp
			onehtzmgbpkjcninefive7bmlnvfhsreightthree
			2822
			3threerbtmxdngpq12oneeightone
			threenine7z
			9bvxxcsnzfive98
			djctwonefourlxshzxzmff313onesixkzxxhrrfour
			sevensevengjbfbzmvlhlseven7bgdrreight
			seven34p5zpmnn
			r27threeqzx27gspmgncgth
			threeeighttwoone1jqghpbbl
			onefqlnr9bmsvjsb2gcl4
			threeqxjjjtqx4four2mbxfive
			5one9qnrzfdsixone
			three184eight
			2hcnineseven1
			onejgnvdndtwoqpdxbnzhkg91sevenrfgv
			hmgseven1fivek866
			seven4four1zpgc
			dl8three5
			7two2
			hbglb9719
			1zsgbsmmgprkmgssvnrbv7
			5sixfourrfbbvmlrjfourl
			three63sixseven5
			seven3eightthree318five
			6brhdvjnz
			onesevenfivefour5four413
			two5689seventhree9
			59nczhdqzdr
			3vsxmbrfkljfxlkxm1x
			6nm6k5three47
			451sixxkcncfqr
			xsixonevns4seven3vlxpfcttwo
			kl6onehlrmxgbfourfour8
			qvfclpxqfivethreeninesixl521
			33hpkbonepsnfp8nine2
			three41fivetzzfvmlsfive5two
			9two6vgvxhnfjone
			six68five8pbgrvl2six
			sphsdpxfdtgvmmtwoone8eight
			z726vlhseven
			nine9ninesix6xmgbsgfmpgxkzgpzlxqnjsqhr
			fourknflljrbrq63five
			42onef6seven
			39njjvzt7threetkccstz
			""";

}
